### ISSUE TITLE
PHP 7 Deprecated Constructors

### ISSUE THREAD

**Issue by shawnhooper** [novaksolutions/infusionsoft-php-sdk#103]
Since upgrading to PHP 7, I get warnings thrown by the WordPress Plugin version of the SDK.  Just wanted to make sure updating this is on the development roadmap before PHP updates again at some point and this breaks. 

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; xmlrpc_client has a deprecated constructor in /var/www/html/wp-content/plugins/infusionsoft-sdk/Infusionsoft/xmlrpc.inc on line 812

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; xmlrpcresp has a deprecated constructor in /var/www/html/wp-content/plugins/infusionsoft-sdk/Infusionsoft/xmlrpc.inc on line 1950

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; xmlrpcmsg has a deprecated constructor in /var/www/html/wp-content/plugins/infusionsoft-sdk/Infusionsoft/xmlrpc.inc on line 2115

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; xmlrpcval has a deprecated constructor in /var/www/html/wp-content/plugins/infusionsoft-sdk/Infusionsoft/xmlrpc.inc on line 2756
```

**Comment by patrick-wyzorski** [comment]
I am running into this issue as well. In fact, I am unable to even suppress these notifications. Would love to see a fix for this issue.

**Comment by joeynovak** [comment]
Hey Guys, I'm working on this right now.  It's a simple fix.

**Comment by joeynovak** [comment]
Patrick,  It looks like this was actually fixed a while ago.  Our latest release in 2016-10-31 of the sdk fixes this problem.  The Wordpress SDK plugin hasn't been updated in a while, but if you update the SDK in the wordpress plugin with the latest version of the sdk in this repo it should work fine.

**Comment by patrick-wyzorski** [comment]
Hey awesome, thanks!

 

Looks like I’ll have to update from the repo then.

 

 

 

Regards,

~Patrick

 

Patrick Wyzorski
Principal WyzGuy Consulting
Brilliant, Innovative Solutions to Monetize Your Business

 936B 7th St., PMB 215
Novato, CA  94945
 <mailto:patrick@WyzGuyConsulting.com> patrick@WyzGuyConsulting.com

+1 (707) 992-0536 (phone)

+1 (855) 999-4892 (FAX)
