### ISSUE TITLE
composer autoload

### ISSUE THREAD

**Issue by MACscr** [novaksolutions/infusionsoft-php-sdk#106]
Why isn't require_once 'vendor/autoload.php'; good enough when installed with composer?

$contact = new Infusionsoft_Contact();
$contact->FirstName = 'John';
$contact->LastName = 'Doe';
$contact->save();

webusr@id-10:/var/www/html/apis$ php infusionsoft-api.php
PHP Fatal error:  Uncaught Error: Class 'Infusionsoft_Contact' not found in /var/www/html/apis/infusionsoft-api.php:8
Stack trace:
#0 {main}
  thrown in /var/www/html/apis/infusionsoft-api.php on line 8

**Comment by MACscr** [comment]
Ugh, if i change it to:

require_once('vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/infusionsoft.php');

I get:

```webusr@id-10:/var/www/html/apis$ php infusionsoft-api.php
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /var/www/html/apis/vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/xmlrpc.inc on line 43
PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/apis/vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/DataService.php:219
Stack trace:
#0 /var/www/html/apis/vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/Generated/Base.php(36): Infusionsoft_DataService::save(Object(Infusionsoft_Contact), NULL)
#1 /var/www/html/apis/infusionsoft-api.php(13): Infusionsoft_Generated_Base->save()
#2 {main}
  thrown in /var/www/html/apis/vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/DataService.php on line 219```

**Comment by calebtr** [comment]
I'm not getting that error when I use your require_once path, but I'm also requiring PHP 5.6 in composer.json.

My php.ini has dl enabled:

    enable_dl = On

I also expected vendor/autoload.php to be enough.

**Comment by lcaleo** [comment]
i put "../" in front of the path and it found it   

"require_once '../vendor/autoload.php';"
