### ISSUE TITLE
Retrieve all custom fields value for specific contact

### ISSUE THREAD

**Issue by supremesupports** [novaksolutions/infusionsoft-php-sdk#108]
Hi,
I've been searching for this solution but haven't found one!
What I'm trying to do is to get value of a custom field for specific contact. Lets say, I've a custom fields named **_myCustomField** with Yes/No value. I've 200 contacts in my list but only 15 contact has value 'Yes' for **_myCustomField**. Lets say I've another custom field **_myCustomField2**. If I run following query:

`$contacts = Infusionsoft_DataService::query( new Infusionsoft_Contact(), array('_myCustomField' => '1') );`

I get an array of 15 records, BUT if I print `$contacts` array then I don't see **_myCustomField** or **_myCustomField2** there. 

So, how do I get value for those two custom field inside my loop? Can someone help me with this?

Thanks!

**Comment by calebtr** [comment]
Have you set up the custom fields with Infusionsoft_Contact::addCustomFIeld ?

        Infusionsoft_Contact::addCustomField('_myCustomField');
        Infusionsoft_Contact::addCustomField('_myCustomField2');

**Comment by supremesupports** [comment]
I didn't know that I have to define `addCustomField` again just before fetching list of contacts. 
Thanks a lot @calebtr !

**Comment by calebtr** [comment]
I'm not sure why you'd have to do it a second time. If you are hitting this snag over and over, you can extend the class to make sure the fields are always added:

    class my_infusionsoft_contact extends Infusionsoft_Contact {
        public function __construct($id = null, $app = null) {
            parent::__construct($id, $app);
            self::addCustomField('_MyCustomField');
            self::addCustomField('_MyOtherCustomField');
        }
    }

Then:

    $contact = new my_infusionsoft_contact();
