### ISSUE TITLE
Retrieve LeadScore for a contact

### ISSUE THREAD

**Issue by jimsdeveloper** [novaksolutions/infusionsoft-php-sdk#109]
Hi,
I am trying to retrieve only the LeadScore for a contact, but I keep getting an error. Not sure where I am going wrong. This is my code

`$contactData = new Infusionsoft_Contact();
$contactData->addCustomField('_LeadScore');
$contactData->load(15861);  //This is the ID of a sample contact inside my Infusionsoft account
print_r($contactData);`

Would appreciate if someone can provide a solution. Thanks.

**Comment by jacoballred** [comment]
The lead score generated by Infusionsoft isn't available via the API. Many people create a custom field for lead score and populate it using their own criteria.
