### ISSUE TITLE
A Reflected XSS vulnerability in this sdk

### ISSUE THREAD

**Issue by jgj212** [novaksolutions/infusionsoft-php-sdk#111]
Hello:
I found a Reflected XSS vulnerability in this sdk.

The vulnerability exists due to insufficient filtration of user-supplied data in 'ContactId' HTTP _REQUEST parameter that will be passed to “infusionsoft-php-sdk-master/Infusionsoft/examples/leadscoring.php”. The infected source code is line 2, there is no protection on $_REQUEST['ContactId']; If $_REQUEST['ContactId'] contains evil js code, line 53 will trigger untrusted code to be excuted on the browser side
![code1](https://cloud.githubusercontent.com/assets/1484292/23243893/d69c42ec-f9bc-11e6-868f-316226e6bd8f.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/infusionsoft-php-sdk-master/Infusionsoft/examples/leadscoring.php?ContactId="><script>alert(1);</script><"

The follow screenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![sc](https://cloud.githubusercontent.com/assets/1484292/23243910/e5685400-f9bc-11e6-9129-27c184a59bff.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech
Email: jgj212@gmail.com

**Comment by jacoballred** [comment]
Thanks! I've added encoding of HTML entities for that, which I think should fix this issue.
