### ISSUE TITLE
How can I add a Tag using InfusionSoft_Contact()

### ISSUE THREAD

**Issue by andersoncsales** [novaksolutions/infusionsoft-php-sdk#113]
It is my code and working perfectly to send a new user, but I dont know how can i apply Tags.

`$AddContact = new Infusionsoft_Contact();
$AddContact->FirstName = 'Jhon';
$AddContact->LastName = 'Due';
$AddContact->Email = 'infusion@infusion.com.br';
$AddContact->save();`

I will use some variables to apply any tags, this is the resume of code.

**Comment by jacoballred** [comment]
Please view the examples page: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#add-a-tag-to-a-contact
