### ISSUE TITLE
Can we check email if it exists or not and update a field?

### ISSUE THREAD

**Issue by andrelmariano** [novaksolutions/infusionsoft-php-sdk#115]
I use this to add a new contact:

**$Contact = new Infusionsoft_Contact ();**

But to not add a contact that already exists I use this:

**$Contact = Infusionsoft_DataService :: query (new Infusionsoft_Contact (), array ('Email' => $ hotmart_mail));**

and

****If (count ($ contact)> 0) {**

**$Contact = array_shift ($ contact); }**

**Else { $Contact = new Infusionsoft_Contact ();****

But in fact I would like to check if the contact exists and if it exists I wanted to update a custom field called _planoclub can you help me ?

**Comment by jacoballred** [comment]
Please use the code from #65 that you commented on earlier.

You would update an existing field just like the code in #65 shows. E.g., to update the name you would do something like:

````php
$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => $hotmart_mail));

if (count($contacts) > 0) {
    $contact = array_shift($contact);
} else {
    $contact = new Infusionsoft_Contact();
}

$contact->FirstName = 'Jim';
$contact->Email = $hotmart_mail;
$contact->save();
````

**Comment by andrelmariano** [comment]
Hello Jacoballred.
This did not work, when I do the test the contact is duplicated, it does not update the contact, it simply creates a new contact. Have a look at my code:

`$contact = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => $hotmart_mail));
if(count($contacts) > 0){
$contact = array_shift($contact);
} else {
$contact = new Infusionsoft_Contact();
}


//---------------------------------------
// Aqui você adiciona o(s) CustomFields
$custom = array(
	'_planoclub',

);
$contact->addCustomFields($custom);


$phone = $phone_local_code . $phone_number;

// Aqui São os Dados que você recebe do Hotmart e passa para o infusion
$contact->FirstName = $first_name;
$contact-> LastName = $last_name;
$contact-> Email = $hotmart_mail;
$contact-> Phone1 = $phone;    
$contact->_planoclub = $plano;
//$contact->_planoclub = $full_price;
$contact-> Id =  Id;
$contact->save();



 // Aqui é o ID da tag que você vai aplicar no contato no caso a Tag de cliente
$groupID = 363;

Infusionsoft_ContactService::addToGroup($contact-> Id,$groupID);
`

**And here the images that prove the duplication of the contacts**
![print](https://cloud.githubusercontent.com/assets/4019432/25136667/03c93f9c-242c-11e7-8de8-f9eb69340976.png)

I would like after checking that there is already a record with the same email it just update the field last name :) help me?

**Comment by jacoballred** [comment]
This line shouldn't be there, since you don't know the contact ID and a new contact wouldn't have an ID set yet: $contact-> Id = Id;

That might be the cause of the issue.

**Comment by jacoballred** [comment]
Also, this:

````php
$contact = array_shift($contact);
````

should be this:

````php
$contact = array_shift($contacts);
````

**Comment by andrelmariano** [comment]
My God, thank you very much for the help :) you saved me hahahaha
