### ISSUE TITLE
EmailAddStatus error for new contacts

### ISSUE THREAD

**Issue by peddie45** [novaksolutions/infusionsoft-php-sdk#117]
I use your API to upload new contacts, with name, email, etc, and a tag. These appear to load correctly into Infusionsoft. We also have a campaign set up in Infusionsoft to send an email to a staff member when a contact gets the tag. The campaign fires, but sometimes gives this error and fails:
 
No records were found for this prepared statement: SELECT CASE WHEN (LastOpenDate IS NOT NULL) THEN DATEDIFF(NOW(), LastOpenDate) ELSE DATEDIFF(NOW(), DateCreated) END FROM EmailAddStatus WHERE EMAIL=?

It looks like there is missing data from the contact record. Could you advise at all?

**Comment by piersaitman** [comment]
It looks like the database hasn't populated the EmailAddStatus table before the campaign fires. If that's the case, it's not a problem with your code, but please comment and close, it would be good to get some clarity.

**Comment by peddie45** [comment]
It looks like we needed to opt in the contact before any sequence takes place. The strange thing is, the above used to work all the time, and still works intermittently.
