### ISSUE TITLE
Error when using OAuth2 Code Example

### ISSUE THREAD

**Issue by pale2hall** [novaksolutions/infusionsoft-php-sdk#119]
Hi there,

Thank you for making this package.  It makes the API much less intimidating than the official php sdk does.

I'm trying to get setup, and I'm trying to run the code on the README.MD, but I'm getting this error:

`Fatal error: Call to undefined method Infusionsoft_App::connect()`

Just to confirm, my config has: 

```
$infusionsoft_host = 'tuxxx.infusionsoft.com'; //my Infusionsoft subdomain when I use my account.
$infusionsoft_api_key = '9xxxxxxxxxxxxxxxxxxxxxcs';  //My API Key as obtained from https://keys.developer.infusionsoft.com/apps/mykeys
```

I'm looking for some guidance.  Thanks!!

**Update:** Just searched through the source code, I don't see a connect method anywhere.

**Update 2:** So, it looks like in app.php `connect()  `was renamed to `initOauthClient()` and the Readme wasn't updated.  My issue still isn't solved, because it's saying: 

`Fatal error: Using $this when not in object context in /var/www/{site}/Infusionsoft/App.php on line 65`

**Comment by pale2hall** [comment]
If anyone could look into this I would really appreciate it.

**Comment by assertdesignuk** [comment]
Hi

I had the same issue.

So instead of:
$app = Infusionsoft_App::connect();

Do:
$app = new Infusionsoft_App;

Hope it helps.
