### ISSUE TITLE
Contact Field Names

### ISSUE THREAD

**Issue by MACscr** [novaksolutions/infusionsoft-php-sdk#122]
How are we supposed to know the format for contact field names? How do we know its $contact->FirstName and not $contact->firstname, etc? Is there a list somewhere? Right now I have something like so:

```
$contact = new Infusionsoft_Contact();
$contact->FirstName = $data['first_name'];
$contact->LastName = $data['last_name'];
$contact->Email = $data['email'];
$contact->save();
```

Id prefer to simply pass a $data array or object that is mapped correctly with the proper keys instead of statically assigning it this way. In addition right now to what im passing now, i need to add zip code and phone number.

Any help is sincerely appreciated.

**Comment by jacoballred** [comment]
The SDK uses the database field names. See: https://developer.infusionsoft.com/docs/table-schema/

**Comment by MACscr** [comment]
Awesome! Thanks!

**Comment by MACscr** [comment]
Jacob,

Thanks again for your reply and apologies if I should open another issue for this, but it all fields do not seem to be showing up at the destination even though I do get a $contact->Id back. Is there any type of verbose response be var_dumping to see what might be wrong?

**Comment by jacoballred** [comment]
Can you provide a code snippet showing how you are setting the fields that aren't making it to Infusionsoft?

**Comment by MACscr** [comment]
Jacob,
I am sure I am setting them right, but they are filled dynamically and maybe I need to add more validation before that point, but I would still think there would be some sort of response from the API if it didnt like something.

**Comment by jacoballred** [comment]
For contacts, most (all?) fields allow any characters. If the fields aren't populating in Infusionsoft then you may be using the wrong field name or you have a bug in your code.

**Comment by MACscr** [comment]
So the only responses are either false or a a contact id? Thats annoying. Oh well.

- Mark

**Comment by jacoballred** [comment]
It'll throw an exception if you do something exceptionally wrong (like trying to write to a read only field).

If some fields are making it to Infusionsoft, then it seems pretty likely there is a bug in your code and you aren't actually setting the fields you think you are setting.

**Comment by BharviManvar** [comment]
Hello 

I am using Same code for Custom Field update data in Contact

$contact = new Infusionsoft_Contact($id);
$contact->FirstName = $data['first_name'];
$contact->LastName = $data['last_name'];
$contact->Email = $data['email'];
$contact->_Message="Test";
$contact->save();

But I want to update  Custom Field data using Custom Field id not a name ,Please Give me the best suggestion,

Thanks,
Bharvi
