### ISSUE TITLE
Pulling all contacts for a tag

### ISSUE THREAD

**Issue by arkitektron** [novaksolutions/infusionsoft-php-sdk#125]
Hello, 

I am successfully using the following code: 

$tagAssignedContacts = Infusionsoft_DataService::query(new Infusionsoft_ContactGroupAssign(), array('GroupId' => $tagId));

However, I am only able to pull 1000 contacts at a time into the array. I need to add code in order to pull the next 1000 contacts, then the next, etc. due to page size of the API. 

Can anyone offer any suggestions? 

Kind regards.

**Comment by cosminsc** [comment]
Try using do{}while{} statement, something like:
```
$all_entries = array();

do{
   $tagAssignedContacts = Infusionsoft_DataService::query(new Infusionsoft_ContactGroupAssign(), array('GroupId' => $tagId));

   foreach($tagAssignedContacts as $item){
      //do something with the results, store in an array maybe
      $all_entries[$item->Id] = $item;
   }

}while(count($tagAssignedContacts) > 0);
```
**Is not tested!**

**Comment by arkitektron** [comment]
This causes a HTTP ERROR 500. I am playing around with this code with limited to no success. I simply need it to list out all of the contact ids that belong to one group / tag.  Could you be a little more specific with the syntax pertaining to that need? Please let me know and I appreciate your help.

**Comment by cosminsc** [comment]
I missed the limit and the pagination parameters. Because I do not have over 1000 contacts I just set the limit to 10 contacts per page, this should work now:
```
$page = 0;
$limit = 10;
$tagId = 92;
$all_entries = array();

do{
	$tagAssignedContacts = Infusionsoft_DataService::query(new Infusionsoft_ContactGroupAssign(), array('GroupId' => $tagId), $limit, $page);

	foreach($tagAssignedContacts as $item){
		$all_entries[] = $item;
	}

	$page++;

}while(count($tagAssignedContacts) > 0);

// echo '<pre>'.print_r($all_entries, 1).'</pre>';exit;
```
