### ISSUE TITLE
Fatal error: Call to undefined method Infusionsoft_DataFormField::getCustomFieldValues() 

### ISSUE THREAD

**Issue by khyler** [novaksolutions/infusionsoft-php-sdk#130]
I'm trying to update a dropdown, custom field using the example provided [here.](https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#add-a-value-to-a-customfield-dropdown)

`$customField = Infusionsoft_CustomFieldService::getCustomField(new Infusionsoft_Contact($_REQUEST["clientid"]), '_Status');
$customField->addValue("Pending");
$customField->save();`

However, this method gives the following error.
**Fatal error: Call to undefined method Infusionsoft_DataFormField::getCustomFieldValues()** 

After searching through the files, I don't seen any reference to this this methods definition. Is there another method I should be using, or is this incomplete?

**Comment by akshayjoshi12** [comment]
I have same issue. Even I cannot add value to custom field. It is showing an error like "Invalid Field Name".
