### ISSUE TITLE
Pushing tag and custom field via Infusionsoft

### ISSUE THREAD

**Issue by BharviManvar** [novaksolutions/infusionsoft-php-sdk#132]
Hello Team,

Please guide me with my following query. I am trying to push (store) data in my infusionsoft contact record in form of tag & custom field. But unfortunately the value is not getting stored in custom field and neither tag is being applied successfully via API. Further , please find the code for custom field api and the error reported.

Kindly help in implementing the same

Code:
$customField = Infusionsoft_CustomFieldService::getCustomField(new
Infusionsoft_Contact(), ‘_Message’);
$customField->addValue($status);
$customField->save();

Error:
Fatal error: Call to undefined method Infusionsoft_DataFormField::getCustomFieldValues() in /home4/steamline/public_html/CI/infusionsoft-php-sdk-master/Infusionsoft/DataFormField.php on line 78

Thanks

**Comment by bhanupartapsingh** [comment]
Hi,

is there any solution regarding this error

**Comment by jacoballred** [comment]
Have you looked over the examples? They show how to set custom fields and add tags to a contact.

https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples

**Comment by bhanupartapsingh** [comment]
Tag is working fine for me it is custom field which is giving error  as you can see screenshot here   https://www.screencast.com/t/Hu2BKyERjEr  and let me know what am i doing wrong

**Comment by jacoballred** [comment]
It looks like you are trying to add a value to a custom dropdown, not set a value on a custom field.

Example, using information from the examples page I linked earlier:

`Infusionsoft_Contact::addCustomField('_Phone');`
`$contact = new Infusionsoft_Contact();`
`$contact->_Phone = $formdata['phone'];`

**Comment by bhanupartapsingh** [comment]
Hi, 

thank you this worked just fine.. Thanks again

**Comment by bhanupartapsingh** [comment]
Hi,  can you provide me code which i can use to send email after a contact is signed up.

**Comment by SmartWeb25** [comment]
This code isn't working anymore. I'm getting this error:
<br />
<b>Deprecated</b>:  Non-static method Infusionsoft_Generated_Contact::addCustomField() should not be called statically, assuming $this from incompatible context in
<b>...IFSController.php</b> on line

My code is   Infusionsoft_Contact::addCustomField('payerid');
       public function getFieldValue($ifs_user_id, $field_name)
    {

        Infusionsoft_Contact::addCustomField('payerid');
        $contact = new Infusionsoft_Contact($ifs_user_id);


        if (!$contact->fieldExists($field_name)) {
            return "field doesn't exist";
        } else {
            return $contact->{$field_name};
        }
    }

    public function setFieldValue($ifs_user_id, $field_name, $field_value)
    {
        $contact = new Infusionsoft_Contact($ifs_user_id);

        if (!$contact->fieldExists($field_name)) {
            $contact->addCustomField($field_name);
        }
        $contact->{$field_name} = $field_value;
        $contact->save();
    }

**Comment by freezey** [comment]
The correct use of the addCustomField() method is to first instantiate an empty Contact object and then call addCustomField on the instantiated Contact.
