### ISSUE TITLE
Can we access  the no of Opt-ins for a specific time span using this api 

### ISSUE THREAD

**Issue by ShreyaAc** [novaksolutions/infusionsoft-php-sdk#133]
1)i want to know the no of opt-ins for my application
2)I want to know the no of email opens for my application(ie no of people who have opened the email sent to them )

**Comment by freezey** [comment]
You'll get better info in the API community forums - those are API questions, not SDK questions.
https://community.infusionsoft.com/c/api

Opt-ins can be found in the EmailAddStatus table. Email Opens are not reported by the API
