### ISSUE TITLE
Email statuses (Types) not being pulled correctly

### ISSUE THREAD

**Issue by zmarakjanbangash** [novaksolutions/infusionsoft-php-sdk#139]
I am trying to pull a contact's email status to see what it is. The purpose is to run an re-engagement campaign on my database of about 40,000 to give contacts the opportunity to re-engage with our content and if they dont take any action, they are unsubscribed automatically. 

Now obviously infusionsoft does not do this natively that is unsub contacts from the campaign builder. But I was hoping to write a script called through a http post that will unsubscribe the contact. 

I think with the recent changes in infusionsoft's email status from plain integer based status i.e. Confirmed (2), Unconfirmed (1) and Opt Out (0), they have moved to a string based type. 

Does anybody know if this SDK is able to handle that and how I can pull and manipulate the email status. Any help on this would be greatly appreciated. 

Thanks.

**Comment by stevejohnson-ilikewp** [comment]
If you haven't figured this out yet...

Email statuses are not attached to the contact record, but to the email record in EmailAddStatus table.

Get the email address of the contact, then query:
`Infusionsoft_DataService::query( new Infusionsoft_EmailAddStatus(), array( 'Email' => $emailAddr ) );`

Just for reference, these are the current email status strings/descriptions at Infusionsoft:
		'SingleOptIn' => 'This person has opted in but not confirmed their email address',
		'UnengagedMarketable' => 'This person has been unengaged for a period of time',
		'DoubleOptin' => 'This person has clicked an email confirmation link.',
		'Confirmed' => 'This person has confirmed their email address.',
		'UnengagedNonMarketable' => 'This person has been unengaged for too long a period of time to be marketed to',
		'NonMarketable' => 'There is no evidence that this person has consented to receive marketing.',
		'Lockdown' => 'This person was added while the app was locked down.',
		'Bounce' => 'This email address has bounced too many times.',
		'HardBounce' => 'This email address has hard bounced.',
		'Manual' => 'This person has opted out of all email marketing.',
		'Admin' => 'This person was manually opted out by an administrator.',
		'ListUnsubscribe' => 'This person has opted out of all email marketing.',
		'Feedback' => 'This person reported spam messages to his/her provider.',
		'Spam' => 'This person provided feedback when opting out.',
		'Invalid' => 'This email address failed the regular expression validation',

**Comment by zmarakjanbangash** [comment]
Hi stevejohnson-ilikewp,

Thank you for your response on this. I appreciate the help. This resolved my issue.
