### ISSUE TITLE
Error:  Non-static method Infusionsoft_Generated_Contact::addCustomField

### ISSUE THREAD

**Issue by SmartWeb25** [novaksolutions/infusionsoft-php-sdk#140]
I've added this line in my config.php file and getting this error: 

Infusionsoft_Contact::addCustomField('custom_field_name');

The error: 
Non-static method Infusionsoft_Generated_Contact::addCustomField

No one getting this error? How to fix it? 
How to get/set custom field value of a contact?

**Comment by freezey** [comment]
addCustomField is not a static method. To use it, first instantiate an empty Contact object and then call $Contact->addCustomField('custom_field_name')
