### ISSUE TITLE
resolve PHP 7.2 warning related to each()

### ISSUE THREAD

**Issue by henryalejo** [novaksolutions/infusionsoft-php-sdk#141]
ErrorException in xmlrpc.inc line 3100:
The each() function is deprecated. This message will be suppressed on further calls
at each(array('string' => 'xxxxxxxxxxxxxxxxxxxxxxxx')) in xmlrpc.inc line 3100

php version:
PHP 7.2.2 (cli) (built: Feb  1 2018 11:50:40) ( NTS )

**Comment by jimsdeveloper** [comment]
I am facing the same exception. Do we have a solution yet?

**Comment by antonioandrade** [comment]
@jimsdeveloper see https://github.com/novaksolutions/infusionsoft-php-sdk/pull/138
