### ISSUE TITLE
getting property values with dot "." in the names in

### ISSUE THREAD

**Issue by mikeHughesNLT** [novaksolutions/infusionsoft-php-sdk#142]
I am going crazy...  I can't get to the properties inside of Infusionsoft_ContactGroupAssign that have periods (dots) in the property names (e.g. Contact.Email).  I noted in 
https://stackoverflow.com/questions/5351018/php-object-attribute-with-dot-in-name   that we should be able to access via { }'s such as in this code example:
```
$contactsForTag = Infusionsoft_DataService::query( new Infusionsoft_ContactGroupAssign(),
	array('GroupId' =>5221), 100, 0,
	array('Contact.Id', 'DateCreated', 'Contact.Email'), $app );//GroupId is a tag id
```
`print_r($contactsForTag);`
`echo '<br> Now drill down <br>';`
`echo $contactsForTag[0]->{'DateCreated'};  //works although {'  ... '} are not needed`
`echo '<br>';`
`echo $contactsForTag[0]->{'Contact.Email'}; //doesn't return anything? `

Not sure what the issues is?

**Comment by jacoballred** [comment]
The "dot" fields aren't in the $tableFields array so the __get method won't let you access them. I'm not sure if this is an oversight or if they weren't originally exposed via the API.

A workaround is to add them as custom fields before trying to access them. For example:
```
$contactsForTag = Infusionsoft_DataService::query( new Infusionsoft_ContactGroupAssign(),
	array('GroupId' =>5221), 100, 0,
	array('Contact.Id', 'DateCreated', 'Contact.Email'), $app );//GroupId is a tag id

$contactGroupAssign = new Infusionsoft_ContactGroupAssign();
$contactGroupAssign->addCustomField('Contact.Id');

foreach ($contactsForTag as $contactForTag) {
    echo $contactForTag->{'Contact.Id'};
}
```

**Comment by mikeHughesNLT** [comment]
Thank you!  Your SDK rocks!
So I did a quick (yet verbose) loom on a follow up question.  https://www.useloom.com/share/4bad28fd56bd4f37b1ad4a85a9f19154  

Basically in the[ Infusionsoft Table schema](https://developer.infusionsoft.com/docs/table-schema/): the Many-to-many table ContactGroupAssign basically links the tagids to contactids.. but why did infusionsoft put all the contact data 'copied' to this basic many to many table?  That contact data is now static right? so if phone is changed in the contact, the phone1 will be what it was when the person was tagged (with the particular tag (groupid) we are querying)?  

Also as discussed in [Loom](https://www.useloom.com/share/4bad28fd56bd4f37b1ad4a85a9f19154  ),  If I pull data from the contact data one at a time in a loop for each contact with a certain tag, is this inefficient code? does it tax the server out if I get to 1000s of contacts with a certain tag?
```
$i = 0;
foreach ($contactsWithId5221 as $contactVal) {
	$tempContact = new Infusionsoft_Contact($contactVal->ContactId);
	$students[$i]['ContactId'] = $tempContact->Id;
	$students[$i]['FirstName'] = $tempContact->FirstName;
	$students[$i]['LastName'] = $tempContact->LastName;
	$students[$i]['Email'] = $tempContact->Email;
	$students[$i]['Phone1'] = $tempContact->Phone1;
	$students[$i]['Tags'] = $tempContact->City;
	//echo $students[$i]['ContactId'] . ' is contact id for ' . $students[$i]['FirstName'].  '<br>' .'end loop ';
	$i++;
}
```

Where the $contactsWithID522  is a comes from the simple code:
```
$contactsForTag = Infusionsoft_DataService::query( new Infusionsoft_ContactGroupAssign(),
	array('GroupId' =>5221));
```

**Comment by jacoballred** [comment]
Thanks for the feedback! I'm glad the SDK has been helpful for you.

I've never used the Contact fields from the ContactGroupAssign table so I'm not positive, but I'm pretty confident they are the live, current values for the contact. You could look at the values for a test client in ContactGroupAssign, change a value in Infusionsoft, then check ContactGroupAssign again to verify this.

If you did want to pull the contact record for each contact ID instead of relying on the values included with the ContactGroupAssign results then you'd want to do that in as few API calls as possible. This prevents hitting the per-second or per-day API limits, and will make your application a lot faster.

You could do something like this:

```
<?php

$contactsForTag = Infusionsoft_DataService::query(new Infusionsoft_ContactGroupAssign(), ['GroupId' =>5221], 1000, 0, ['ContactId'], $app);

$allContactIds = [];
$i = 0;

foreach ($contactsForTag as $contactForTag) {
    $allContactIds = $contactForTag->ContactId;
}

do {
    // Only handle 1000 at a time
    $contactIds = array_slice($allContactIds, $i, 1000);

    // Increment offset
    $i += 1000;

    // Infusionsoft requires values to be actual integers
    $contactIds = array_map('intval', $contactIds);

    // Get all contact objects at once
    if (!empty($contactIds)) {
        $infusionsoftContacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), ['Id' => array_values($contactIds)]);

        // Do something with the contacts
        foreach ($infusionsoftContacts as $contact) {
            // You can do whatever you want with the contact here.
            // For example:
            echo 'Contact name: ';
            echo htmlspecialchars($contact->FirstName . ' ' . $contact->LastName) . '<br>';
        }
    }
} while (!empty($contactIds));
```
Note the do...while loop. You'll want to do something similar with the DataService query because Infusionsoft only allows you to pull up to 1000 records at a time.

Hope this helps!

**Comment by mikeHughesNLT** [comment]
This does help!  Thank you for your time.  Much appreciated.
I will play with this where say we have 500 contacts and each contacts we are focusing on.  Further, say..7 tags on average for each contact.  That will be 3500 records in the contact-tag linking table ContactGroupAssign and I can manipulate this large array in the PHP...  I will basically filter per contact and have a large switch:  -  case: operation to create another array to hold contact tag data that is serialized and output to WPDataTables.. (or pulled from WPDataTables...  I can send final code here when done if anyone else is doing a similar task.  Thanks!
