### ISSUE TITLE
oAuth2 authentication

### ISSUE THREAD

**Issue by qwebltd** [novaksolutions/infusionsoft-php-sdk#146]
Combining the resolutions of various previous issue reports to fix the provided oAuth sample, I now have the following config.php:

	$infusionsoft_host = $infusionSoftHost;
	$infusionsoft_api_key = $infusionSoftClientID;
	Infusionsoft_OAuth2::$clientId = $infusionSoftClientID;
	Infusionsoft_OAuth2::$clientSecret = $infusionSoftClientSecret;

	Infusionsoft_AppPool::addApp(new Infusionsoft_App($infusionsoft_host, $infusionsoft_api_key, 443));

And the following oAuth script:

	require('required/Infusionsoft/infusionsoft.php');
	require('required/Infusionsoft/config.php');

	$cleanRedirectUri = explode('?', $_SERVER['REQUEST_URI'], 2);
	Infusionsoft_OAuth2::$redirectUri = 'http'.(isset($_SERVER['HTTPS']) ? 's' : '').'://'.$_SERVER['HTTP_HOST'].$cleanRedirectUri[0];

	Infusionsoft_OAuth2::processAuthenticationResponseIfPresent();

	$app = new Infusionsoft_App;

	if(!$app->hasTokens()){
		header("Location: " . Infusionsoft_OAuth2::getAuthorizationUrl());
		die();
	}

	$results = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('FirstName' => '%'), 2);
	echo '<pre>'; var_dump($results); echo '</pre>';

This successfully takes me to an access grant page, but after granting results in this:

"Fatal error: Uncaught Error: Call to a member function saveTokens() on null"

**Comment by harshanakaru** [comment]
Anyone has a solution for this? Still struggling to get past this.

**Comment by freezey** [comment]
You need to implement a TokenStorageProvider that the SDK can call to
retrieve and set the tokens generated in the oauth process.  You can look
at the TokenStorageProvider interface and the JsonTokenStorageProvider
class for examples on what you need to build.

**Comment by harshanakaru** [comment]
Hi @freezey ,

I'm kind of new to infusionsoft integration. I'm trying to build a simple integration between E-commerce site and infusionsoft. What i'm about to ask maybe idiotic but here goes :D 

I see an interface with save and get token methods. Do i have to create these methods on the same app.php or create a new class called tokenStorageProvider and implement those two methods? and also do I have to write to store the token on a database or a file? Furthermore, does this storage of tokens are being used to get new tokens from infusionsoft?

Thank you for your help 👍

**Comment by freezey** [comment]
Correct - you have to create a new class (with a unique class name) that
implements TokenStorageProvider (look at the JsonTokenStorageProvider for
an example). Your class will use those methods named in the
TokenStorageProvider interface to save the tokens to database or to disk
and retrieve them on demand.

You will want to do a quick read on what a php Interface is and what it
means for a class to implement an interface.

**Comment by harshanakaru** [comment]
@freezey  I can't seem to find the JsonTokenStorageProvider file :S. Any Idea where the file is ?

**Comment by qwebltd** [comment]
@harshanakaru I'll be honest, I gave up after starting this thread since it received no response, and wrote my own library in the end. Happy to share the code. Should work in PHP 5.6+ (and possibly below, but untested), and it's really simple.

Very, very minimal functionality though - we only needed the ability to post newsletter signups to an Infusionsoft list so this library just handles the tokens and submitting new contacts. It's absolutely not intended to be a replacement for infusionsoft-php-sdk.

The code incorporates dbQuery(), dbFetch(), and dbEscape() functions which are part of our own database library. You'll want to replace those with standard MySQL functions but that should be easy enough and there aren't many instances.

The code requires a single database table for remembering the tokens, so run the SQL within database.sql to add this table to your existing database. Then modify infusionsoft-oauth.php to include your usual database globals and whatnot + to populate the infusionsoft variables (you should move those into your globals file really, as they're needed by any pages that use the library). Once set up, run this file in a web browser and the database table should populate itself with tokens. You can then kill this file for security - there's a helpful die(); at the top to just uncomment for that.

Then you just need to require_once() the infusionsoft.php file at the top of any page that needs integration. To submit a newsletter subscription is then as simple as this:

`$token = infusionsoftToken();

if(!infusionsoftSearchByEmail($token, $_POST['fldEmail']))
	infusionsoftCreateContact($token, $_POST); // Ref the infusionsoft.php file for expected field names

infusionsoftOptInEmail($token, $_POST['fldEmail']);`

Hope this helps. I'll write a proper blog post for this one day!

[Infusionsoft.zip](https://github.com/novaksolutions/infusionsoft-php-sdk/files/2598937/Infusionsoft.zip)
