### ISSUE TITLE
Assigning/removing multiple tags is computationally expensive

### ISSUE THREAD

**Issue by philipdowner** [novaksolutions/infusionsoft-php-sdk#147]
The only way I can see to remove multiple tags (groups) is using the following code. Unfortunately this means a number of additional API calls - something that quickly become computationally expensive when working through large groups of contacts and tags.

Any suggestions on a better way to handle bulk adding/removing tags from a contact?

```php
$contactId = 100;
$tagsToRemove = [123, 124, 125];

//-- This works
foreach( $tagsToRemove as $tag ) {
    Infusionsoft_ContactService::removeFromGroup($contactId, $tag);
}

//-- This does not work
$contact = new Infusionsoft_Contact($contactId);
if( is_null($contact->Groups) ) $contact->Groups = '';
$currentTags = explode(',', $contact->Groups);
$contact->Groups = implode(',', array_diff($currentTags, $tagsToRemove));
$contact->save();
```

**Comment by jacoballred** [comment]
The xml-rpc API that this SDK uses can only add or remove one tag at a time.

**Comment by philipdowner** [comment]
Thanks for the response @jacoballred!
