### ISSUE TITLE
ContactAction doesn't have ObjectType (enum)

### ISSUE THREAD

**Issue by jchimene** [novaksolutions/infusionsoft-php-sdk#15]

**Comment by bajax** [comment]
I've submitted a pull request to fix this issue, if they accept it.  In the meantime, you can access this information by calling addCustomField on the object you want this info for before you load it (without a leading underscore).. 

All addCustomField does is insert the field name to the end of an internal array that also contains all the "vanilla" fields by default.  If Infusionsoft ever adds more fields, you can access them this way without having to wait for an update to the SDK.
