### ISSUE TITLE
How to add custom TimeZone value insert in infusionsoft

### ISSUE THREAD

**Issue by Thameemans** [novaksolutions/infusionsoft-php-sdk#153]
I had try to save the timezone, but its not saved

**Comment by jacoballred** [comment]
Can you provide an example of your code?

**Comment by Thameemans** [comment]
Example code:

In php I had to set Timezone like,

$Time_zone = 'Asia/Kolkata';

Using Your PHP SDK i had tried like this

$contactNew = new Infusionsoft_Contact();
$contactNew->TimeZone= $Time_zone;
$contactNew->save(); 

But i got a error like this


Fatal error: Uncaught exception 'Exception' with message 'Invalid Field Name: TimeZone' in /home/infusionsoft-php-sdk/Infusionsoft/Generated/Base.php:87

Infusionsoft_Generated_Base->__set('TimeZone', 'Asia/Kolkata') #1

**Comment by jacoballred** [comment]
Can you confirm you are using the latest code? That error would indicate that you are using an old version of the SDK.
