### ISSUE TITLE
PHP Fatal error:  Uncaught Failed to invoke method query in class

### ISSUE THREAD

**Issue by adriansavage** [novaksolutions/infusionsoft-php-sdk#16]
Sorry if this is a lame newbie question, but I'm getting the following error occasionally when running queries against the Contact table:

PHP Fatal error:  Uncaught Failed to invoke method query in class com.infusionsoft.api.xmlrpc.XmlRpcDataService: Statement cancelled due to client request
Attempted: 1 time(s).
  thrown in /usr/local/src/isdb/Infusionsoft/App.php on line 101

Is this because I'm not doing sufficient error handling and need to add a retry in, or is this an issue with the SDK?

Many thanks,

Adrian

**Comment by jacoballred** [comment]
Can you provide a snippet of the code you are running?

**Comment by adriansavage** [comment]
It's a variation of your exporter.php code from the examples.  It seems to fail randomly after lots of iterations but with an unpredicatable iteration number:

        $page = 0;
        do{
                $object_fields = $object->getFields();
                printf("Fetching page %d\n", $page);
                if(in_array('Id', $object_fields)){
                        $results = Infusionsoft_DataService::queryWithOrderBy(new $class_name(), array('Id' => '%'), 'Id', true, 1000, $page );
                } else {
                        $results = Infusionsoft_DataService::queryWithOrderBy(new $class_name(), array($object_fields[0] => '%'), $object_fields[0], true, 1000, $page );
                }
                
                foreach($results as $result){
                        if ($table == 'ContactGroupAssign') {
                                addRowToTableCGA($table, $result->toArray(), $iteration);                               
                        } else {
                                addRowToTable($table, $result->toArray(), $iteration);
                        }
                }
                $page++;
        }while(count($results) > 0);

**Comment by jacoballred** [comment]
Yes, you'll need to add some additional error handling so you can retry if the API call fails. This happens with the Infusionsoft API occasionally no matter which SDK you choose to use.
