### ISSUE TITLE
how to add resthook?

### ISSUE THREAD

**Issue by xemacscode** [novaksolutions/infusionsoft-php-sdk#160]
I just want to know how to add resthook using this sdk?

**Comment by joeynovak** [comment]
This SDK is for the legacy API which does not support resthooks.  We have a very incomplete newer version here - https://github.com/novaksolutions/infusionsoft-rest-php-sdk. one of the few features it does implment is registering resthooks but we don't have any documentation for this, so I would recommend you use Infusionsoft's official php sdk instead.
