### ISSUE TITLE
Uncaught CURL error: HTTP/2 stream 0 was not closed cleanly

### ISSUE THREAD

**Issue by jake-newsom** [novaksolutions/infusionsoft-php-sdk#161]
Posting here as I'm not sure what we need to do to fix this from our script... 

We run a daily cronjob to send 2 separate emails out, 1 of each to a different group of Infusionsoft contacts. Twice in the last couple of weeks Infusionsoft has crapped out and returned a 524 error on us after sending one of the emails. 

We wrote a second script that's the same as the first, except it only sends the second email. However when we try to run this manually after the cronjob script fails, we receive the error: 

`Fatal error: Uncaught CURL error: HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
Attempted: 1 time(s).
  thrown in /home/kcmcrew/recurring_scripts/infusionsoft-sdk/Infusionsoft/App.php on line 193`

Our script, for reference, with minor edits to remove our data: https://hastebin.com/bosogigidu.xml

**Comment by jchimene** [comment]
WAG: Try fiddling with CURLOPT_HTTP_VERSION
I've never seen this error before even after 5 yrs. of using this SDK
Not sure why you're creating an email template, but that's another question...

**Comment by jake-newsom** [comment]
As far as we're aware, it's the only way to take an RSS feed and create an email with the new post each day and send it out to our Infusionsoft contacts in a way that it shows in the contact's email history. 

If you know of a better method feel free to let me know. 

I saw the CURLOPT_HTTP_VERSION stuff on google but my understanding is that's only useful on Curl version 7.62.0 and our shows curl 7.19.7 when I run curl -V ... So I would think our curl is already using the suggested HTTP_VERSION_1_1

Regardless, I can't seem to find how I would do that from our code unless we should edit the infusionsoft-php-sdk files?

**Comment by jchimene** [comment]
I was going by the error reference to HTTP/2
To attach to email history, I use the corresponding API call. But, obviously a template works too.

**Comment by joeynovak** [comment]
Hey Jake,

I haven't seen this either and am not sure what it is.  I would probably do all the basics (update curl, etc...) and see if the error goes away.  If you edit the sdk and are able to fix the problem be sure to send a pull request.  Sorry I can't be of more help right now.
