### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rogerdcarvalho** [novaksolutions/infusionsoft-php-sdk#165]
Been using this SDK for 2 years without issue. Suddenly today I get the following error:

    Fatal error: Uncaught String index out of range: -4 Attempted: 1 time(s). thrown in /srv/users/serverpilot/apps/funfitt/public/Infusionsoft/App.php on line 193

Nothing changed on my end.

Any idea what this could be?

**Comment by joeynovak** [comment]
Hi Roger,

I didn't see this ticket until now, did you find out what the problem was?

**Comment by rogerdcarvalho** [comment]
I think it must have been on Infusionsoft side, as retrying it now it started to work again. I didn't end up having to change any of the code.

**Comment by joeynovak** [comment]
Cool, sorry about not helping you out here.  We don't change the core part of the SDK often (if ever) so if it breaks, 99 times out of 100 it's Infusionsoft :(

**Comment by rogerdcarvalho** [comment]
No worries!
