### ISSUE TITLE
How do I add a tag to a contact?

### ISSUE THREAD

**Issue by peterbournecommunications** [novaksolutions/infusionsoft-php-sdk#17]
Hi,

I'd like to use your SDK and the API to assign a Tag (Group) to a given contact.

I've successfully queried IS using your SDK to get the contact Id and GroupId... but can't seem to use the following code without the page failing (no error information on my hosting - sorry):

$newtagapply = new Infusionsoft_ContactGroupAssign();
$newtagapply->ContactGroup = $passedtag; //string
$newtagapply->ContactId = $passedid; //int
$newtagapply->GroupId = $tagID; //int
$newtagapply->save();

Many thanks in advance,

Peter

**Comment by peterbournecommunications** [comment]
A similar issue when creating a new Group. This also fails....

$newtag = new Infusionsoft_ContactGroup();
$newtag->GroupCategoryId = 161;
$newtag->Groupname = "example tag";
$newtag->save();

**Comment by jacoballred** [comment]
Tags are added using the ContactService, like this:

```php
$newtagapply = new Infusionsoft_ContactService();
$newtagapply->addToGroup($passedid, $tagID);
```

**Comment by peterbournecommunications** [comment]
Thanks Jacob for the quick response.

Apologies for not replying sooner - the email notification on this must be in my junk.
