### ISSUE TITLE
Sample code for working with two different Infusionsoft apps at the same time

### ISSUE THREAD

**Issue by adriansavage** [novaksolutions/infusionsoft-php-sdk#18]
Hi,

I'm writing some code that will be interfacing to two different Infusionsoft apps and I'm not clear what the best practice way is of writing code that will connect to the correct app on demand.  Ideally I need to create two instances of an API object but my understanding of PHP isn't good enough (yet!) to deduce how to do this from the code and examples you provide.

Do you have a snippet available that might illustrate exactly how to do it, or have some documentation that explains this which I might have missed?

Many thanks,

Adrian

**Comment by tri3media** [comment]
I would also find this helpful – thanks.

**Comment by joeynovak** [comment]
Hey Guys,

Here you go: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#multi-app-support

Joey

**Comment by tri3media** [comment]
Thanks Joey!

**Comment by joeynovak** [comment]
No problem, I'm curious, what are you using it for?  I'm on the fence about
fixing the custom field issues, if you can give me some background, it may
make it into our 1.0 release.

Joey

**Comment by tri3media** [comment]
I’m trying to fix a rather convoluted sales/membership issue between 2 apps we have.

I have implemented the ‘relationship’ between the two apps as a temporary fix but need to clean up custom fields and actions to make it work the way the owner’s wanting it to work.
