### ISSUE TITLE
Exporter.php Isn't working...

### ISSUE THREAD

**Issue by Matts2009** [novaksolutions/infusionsoft-php-sdk#19]
I downloaded the SDK and setup my config file with the proper IS-appname / API key. The test connectivity came back successful, and when I clicked on the "Exporter" link on the "index.php" page it gives me an error. Is there something that needs to be done after downloading the SDK to get the "exporter.php" link to function properly?

**Comment by joeynovak** [comment]
Hey Matts,

Yeah, it's broken.  (Sorry for taking so long to get back to you).  It isn't on our radar to fix this at the moment, as we're working on the new version of the sdk, and adding OAuth support.
