### ISSUE TITLE
Uncaught CURL error

### ISSUE THREAD

**Issue by amitambekar** [novaksolutions/infusionsoft-php-sdk#21]
Fatal error: Uncaught CURL error: Could not resolve host: https; Host not found Attempted: 1 time(s). thrown in E:\xampp\htdocs\projects\Amit\sign-up\infusionsoft-php-sdk-master\Infusionsoft\App.php on line 101

error coming while executing example.php

**Comment by jacoballred** [comment]
Looks like a configuration issue. Can you paste your config.php, with your API key redacted?

**Comment by amitambekar** [comment]
yeah issue solved :)

**Comment by amitambekar** [comment]
yeah issue solved :)
