### ISSUE TITLE
Is this the latest SDK ??

### ISSUE THREAD

**Issue by swarnenduDutta** [novaksolutions/infusionsoft-php-sdk#26]
Hi 
Thanks for the SDK...
Can we use this SDK in our production site ?? 

https://github.com/infusionsoft/PHP-iSDK is deprecated and recommends to use https://github.com/infusionsoft/infusionsoft-php

**Comment by joeynovak** [comment]
Hey,

Yes, the master branch is VERY stable and is what we use on all of our Internal stuff.  It isn't the "Official" sdk from Infusionsoft, but we think it's way better.

Joey

**Comment by joeynovak** [comment]
P.S.  The latest, but unstable version is the 1.0.0-dev branch.  It is going to be awesome, but it's not ready yet.

**Comment by swarnenduDutta** [comment]
Thanks a lot :)
