### ISSUE TITLE
How to add custom field values to an existing contact

### ISSUE THREAD

**Issue by swarnenduDutta** [novaksolutions/infusionsoft-php-sdk#27]
I want to add values to custom fields values(that may o may not have values)..but the code i followed from the example throws exception..

**Comment by joeynovak** [comment]
Hey,  

Did you tell the sdk about the custom field by calling "addCustomField" on the object you are working with?  This is in the installation section here: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#installation

Also, I saw your comment on ContactGroup.GroupName.  The exception you pasted in there had "Group Name".  It should not have a space.

Joey

**Comment by swarnenduDutta** [comment]
$customField = Infusionsoft_CustomFieldService::getCustomField(new Infusionsoft_Contact($found->Id), '_IPCountry');
$customField->addValue('IND');
$customField->save();

this is my code...it dsnt work..nothing gets stored...

**Comment by joeynovak** [comment]
Oh, I see, my bad.  I'll look at that.

**Comment by vikaswalia1988** [comment]
I have same issue for custom field. Please provide me solution.

Thanks

**Comment by bhanupartapsingh** [comment]
Hi,

any solution regarding above issue. i am using code  like in screenshot  https://www.screencast.com/t/Hu2BKyERjEr  and getting fatal error

**Comment by jacoballred** [comment]
Please look at the examples page, specifically the Installation instructions that go over how to let the SDK know about a custom field: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#installation

Setting a custom field isn't any different than setting a standard field. Example:
`$contact = new Infusionsoft_Contact();`
`$contact->_SomeCustomField = 'Some Value';`

**Comment by vikaswalia1988** [comment]
Its better to use API provided by infusion soft.

I did tried with novaksolution API but got stuck in betwwen development
after that I shifted to API provided by infusion soft and it really works
well.



Thanks,

Vikas Walia
