### ISSUE TITLE
Composer Integration

### ISSUE THREAD

**Issue by mcorrigan** [novaksolutions/infusionsoft-php-sdk#28]
What would you suggest for using this library as a composer dependency without modifying the config file in project directory?

**Comment by elvismdev** [comment]
So is this currently possible to install via composer? like:

`composer require novaksolutions/infusionsoft-php-sdk`

Found this library on packagist https://packagist.org/packages/novaksolutions/infusionsoft-php-sdk but while trying to install it on my `vendor` folder via composer seems like it fails?

```
DELL-XPS:middleware-to-infusionsoft emorales$ composer require novaksolutions/infusionsoft-php-sdk

                                                                               
  [InvalidArgumentException]                                                   
  Could not find package novaksolutions/infusionsoft-php-sdk at any version f  
  or your minimum-stability (stable). Check the package spelling or your mini  
  mum-stability
```

**Comment by elvismdev** [comment]
Please any tips or response on this about how to manage this SDK via composer? I'd like to use it in a Symfony2 project and even if is not ready to autoload it's classes by composer i'd like to use it just to manage it's installation into the vendors folder. 

Thank you

**Comment by elvismdev** [comment]
I think I found it, something like this will clone into my `vendor` folder always the [`master`](https://github.com/novaksolutions/infusionsoft-php-sdk/tree/master) branch?

```
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/novaksolutions/infusionsoft-php-sdk"
        }
    ],
    "require": {
        "novaksolutions/infusionsoft-php-sdk": "dev-master"
    }
}
```

Will later `composer update` keep it updated by cloning the latest commits from [`master`](https://github.com/novaksolutions/infusionsoft-php-sdk/tree/master)?

**Comment by joeynovak** [comment]
Hey, sorry for the delay on this.  I think the problem may be because the package isn't "stable".  The packagist page is here: https://packagist.org/packages/novaksolutions/infusionsoft-php-sdk,  I think if you specify the version as "dev-master" when you try to add it via the command line it will work as well.
