### ISSUE TITLE
No way to add a group.

### ISSUE THREAD

**Issue by kekcleader** [novaksolutions/infusionsoft-php-sdk#29]
I can add a tag to a newly created contact using something like:
Infusionsoft_ContactService::addToGroup($cid, $tag_id);
but I don't know the $tag_id if it does not exist, so I need to create it. There is no way to do it using the PHP SDK, right?

**Comment by jchimene** [comment]
> There is no way to do it using the PHP SDK, right?
It's the same underlying API, just a different technique. The Infusionsoft API supports this, so this SDK does as well. It's just not obvious or documented in the Infusionsoft documentation.
For this SDK, you instantiate the required objects, and use the save() method. I think the Infusionsoft SDK is slightly better in this regard in that it requires fewer steps. I'm sure either Joey or Jacob will chime in if I'm wrong about the following steps:
1) Instantiate a ContactGroupCategory object, set the appropriate values, save() it, capture the new category ID.
2) Instantiate a new ContactGroup object, set the GroupCategoryId value using the value obtained in (1) as well as any other values, save() it, capture the resulting tag ID.

**Comment by kekcleader** [comment]
Thanks for the quick response!
Can I see some code examples or know where to look for them? It's hard to find something about that in Google, as there are a lot of other SDKs and SDK versions.
How do I instantiate a ContactGroupCategory object? There is no such class in the SDK I'm using.

**Comment by jchimene** [comment]
I don't have examples for the Novak SDK, I was using the Infusionsoft SDK as the basis for my response.
The class ContactGroupCategory certainly exists in the Novak SDK, as it's automatically generated by their in-house tool from the list of Infusionsoft's publicly available tables.

**Comment by kekcleader** [comment]
What is Novak SDK?
I'm new to Infusionsoft and don't know the terminology, I'm using infusionsoft-php-sdk

**Comment by kekcleader** [comment]
Do you mean I should use this https://developer.infusionsoft.com/docs/xml-rpc/#data-create-a-record ?

**Comment by jchimene** [comment]
infusionsoft-php-sdk === Novak SDK.
