### ISSUE TITLE
Can't save custom field

### ISSUE THREAD

**Issue by blkinney** [novaksolutions/infusionsoft-php-sdk#30]
I'm trying to save a custom field on a user. Here is my code (Wordpress):

```
include('Infusionsoft/infusionsoft.php');
$current_user = wp_get_current_user();
$lesson_name = '_' + get_the_title();
print_r($lesson_name);
$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Username' => $current_user->user_login));
print_r($contacts);
$contact = array_shift($contacts);
print_r($contact);
$custom_field = $contact->$lesson_name;
print_r($custom_field);
$custom_field->addValue('TRUE');
print_r($custom_field);
$custom_field->save();
$contact->save();
```

I'm finding the contact just fine but the code breaks when I'm trying to find the custom field. the custom field should be name: _Getting Free of Credit Card Debt Quiz. As a side note if the custom field is a yes/no field how do I toggle the yes/no?

**Comment by bajax** [comment]
You have to add the custom field to a contact before you call a dataservice query.  You'd have to do something like this:

    $contact_prototype = new Infusionsoft_Contact();
    $contact_prototype->addCustomField('_CustomFieldName');
    $contacts = Infusionsoft_DataService::query($contact_prototype, /*Your query vars etc... this is pseudocode */);

Afterwards you'll have access to load and save that particular custom field.
