### ISSUE TITLE
Installation instructions aren't correct

### ISSUE THREAD

**Issue by jchimene** [novaksolutions/infusionsoft-php-sdk#31]
# Try the clone command in the instructions
    % git clone git@github.com:novaksolutions/infusionsoft-php-sdk.git      
    Cloning into 'infusionsoft-php-sdk'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights and the repository exists.
# Now use the github suggested clone
    % git clone https://github.com/novaksolutions/infusionsoft-php-sdk.git
    Cloning into 'infusionsoft-php-sdk'...
    remote: Counting objects: 2565, done.
    remote: Total 2565 (delta 0), reused 0 (delta 0), pack-reused 2565
    Receiving objects: 100% (2565/2565), 962.86 KiB | 1.23 MiB/s, done.
    Resolving deltas: 100% (1616/1616), done.
    Checking connectivity... done.

**Comment by joeynovak** [comment]
Yeah, the first set of instructions are for people who have their public key registered with github, I would highly recommend sticking with the first method and getting your public key working.

**Comment by joeynovak** [comment]
But, I've updated the README for future users.
