### ISSUE TITLE
Problem trying to create blank order

### ISSUE THREAD

**Issue by swyse5** [novaksolutions/infusionsoft-php-sdk#33]
When making the following API call:
```
POST https://fm260.infusionsoft.com/api/xmlrpc

Authorization: Bearer <access_token>
Content-Type: application/xml

<methodCall>
  <methodName>InvoiceService.createBlankOrder</methodName>
  <params>
    <param>
      <value><int>22</int></value>
    </param>
    <param>
      <value><string>hello world</string></value>
    </param>
    <param>
      <value><dateTime.iso8601>20080908T00:00:00</dateTime.iso8601></value>
    </param>
    <param>
      <value><int>2</int></value>
    </param>
    <param>
      <value><int>2</int></value>
    </param>
  </params>
</methodCall>
```

I always receive the following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
    <fault>
        <value>
            <struct>
                <member>
                    <name>faultCode</name>
                    <value>
                        <i4>0</i4>
                    </value>
                </member>
                <member>
                    <name>faultString</name>
                    <value>No method matching arguments: java.lang.Integer, java.lang.String, java.util.Date, java.lang.Integer</value>
                </member>
            </struct>
        </value>
    </fault>
</methodResponse>
```

I see I'm not the first to receive an error like this, however I have copy and pasted this request from your API documentation and I can't seem to figure out what I have wrong.  My HTTP client is just POSTMAN, as I just wanted to get a request working before I start writing code.  Any help would be much appreciated!

**Comment by joeynovak** [comment]
Hi,

Can you email me the php file that is creating the problem?  joey@novaksolutions.com

Make sure you don't include API credentials.

Thanks!

Joey

**Comment by swyse5** [comment]
I'm actually not using any PHP file. I only posted in that Github forum because it was the most popular. I was trying to make a straight HTTP call using Postman. I was copying straight from the Infusionsoft docs online, and couldn't get any calls to work.




Stuart WyseMiami University, Class of 2017

Computer Science Major

**Comment by hpss007** [comment]
I am trying to create a blank order via C# using CookComputing.XmlRpcV2 and isdnAPI assemblies

code i am using
 int order = isdnAPI.createBlankOrder(Id, EventType, strdt2,0,0);
id= 2246
EventType = "XYZ"
Strdt2 = Datetime variable returning date

i am getting -1 in order variable. which is not correct.

**Comment by jacoballred** [comment]
I recommend posting your question on the Infusionsoft API forum: http://community.infusionsoft.com/forumdisplay.php/9-API-amp-Custom-Development

We don't provide support for the API, just our implementation of the SDK.
