### ISSUE TITLE
Accented characters not returned properly

### ISSUE THREAD

**Issue by ftrudeau** [novaksolutions/infusionsoft-php-sdk#34]
Contact information in IS contains accented characters, which are incorrectly returned by the OO SDK. Client's request_charset_encoding is set to UTF-8 in App.php.

Québec -> Qu;bec
Frédéric -> Fr;d;ric
Montréal -> Montr;al

**Comment by ftrudeau** [comment]
See return of $this->client->send in App.php ...

As you can see, raw data is fine.

`[raw_data] => HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Pragma: no-cache
Cache-Control: no-cache, no-store
Expires: Mon, 20 Jul 2015 11:54:03 GMT
Content-Type: text/xml;charset=UTF-8
Content-Encoding: gzip
Vary: Accept-Encoding
Date: Sun, 19 Jul 2015 23:54:02 GMT
Connection: close
Set-Cookie: app-lb=!gell0clhsbpZZidgcOos6QUUDc5trb6kDQG4aHAblikQo6eCa25DefPbKyzVkQi4OiQ7WeV75qQEgw==; path=/

Phone2TypeBureauPhone3TypeBureauLeadSourceId0Passwordjob314LastNameTrudeauPostalCode2H1W 2Z4State2QuébecCountry2CanadaFirstNameFrédéricPhone5TypeBureauStreetAddress13529 DavisonFax2TypeBureauAddress2Street13529 DavisonLastUpdatedBy146301Validated0Fax1TypeBureauCompanyID0LastUpdated20150719T19:53:56Websitehttp://ftrudeau.mePhone4TypeBureauDateCreated20150708T16:08:38CountryCanadaCityMontréalPostalCodeH1W 2Z4StateQuébecEmailftrudeau@gmail.comAccountId0City2MontréalUsernameftrudeauCreatedBy-1Phone1TypeBureauId146589OwnerID0
)`

**Comment by ftrudeau** [comment]
Fixed by commenting out line # 2647

```
$data = preg_replace(array('/\&#[0-9]{1,4}/'),'', $data);
```

**Comment by joeynovak** [comment]
Thanks for keeping us up to date on this.  I've been worried about that line for a while, it is there to prevent some other issues with Infusionsoft passing back invalid XML characters which causes xmlrpc.inc to throw an exception while parsing the response.  But, I think it was changed to be too broad, it used to only replace a few specific characters, but someone on our team changed it to be more of a blanket search and replace.  We'll look into it.

**Comment by ftrudeau** [comment]
Well, it's doubly problematic, and just a terrible hack, IMHO ! ; ) For starters, I see no valid reason why you would want to strip out unicode utf-8 encoded chars from the source. Also, the reason why Québec became Qu;bec is that the preg_replace rule is stripping out only part of the code, leaving the semicolon all alone.

So &#233; became ; 

Glad I could be of any help ; )

FT

**Comment by jchimene** [comment]
The back-end database is 8859-1. Normally, acute & grave e would be
maintained.  Other UTF-8 can cause an SQL exception thrown by the back-end.
I stole WordPress code to remap UTF-8 to 8859-1
