### ISSUE TITLE
Strict standards violation: Infusionsoft_ProductService vs. Infusionsoft_Service

### ISSUE THREAD

**Issue by jchimene** [novaksolutions/infusionsoft-php-sdk#35]
Strict Standards: Declaration of Infusionsoft_ProductService::ping() should be compatible with Infusionsoft_Service::ping($serviceName, Infusionsoft_App $app = NULL) in vendor/novaksolutions/infusionsoft-php-sdk/Infusionsoft/ProductService.php on line 2

**Comment by joeynovak** [comment]
Hey Jeff,

Keep these issue reports coming :)  This is fixed in our dev branch.  I changed ping to only be on Infusionsoft/Service instead of on every service.

Joey
