### ISSUE TITLE
OAuth2 - Empty Access Token

### ISSUE THREAD

**Issue by sankarnarayan** [novaksolutions/infusionsoft-php-sdk#36]
OAuth Server response with warning message and AccessToken, RefreshToken, ExpiryTime are not created in infusionsoft-tokens.php.

#### Code I used to create object ####
     if(isset($_GET['code']))
     {
           $tsp = new Infusionsoft_SimpleJsonFileTokenStorageProvider;
           $tsp->getTokens('TestCode123');
           $app = Infusionsoft_App::connect($tsp);
           if($app->hasTokens())
           {

#### Server Response ####
Warning: array_keys() expects parameter 1 to be array, null given in /home/mmm/public_html/mmm/OAuth/Infusionsoft/SimpleJsonFileTokenStorageProvider.php on line 49

      Hostname: .infusionsoft.com

      BB

      DD

      Details:
      Infusionsoft_App Object
      (
          [usingOAuth:protected] => 1
          [tokenStorageProvider:protected] => Infusionsoft_SimpleJsonFileTokenStorageProvider Object
              (
                  [fileName] => infusionsoft-tokens.php
              )

          [hostname:protected] => .infusionsoft.com
          [accessToken:protected] => 
          [apiKey:protected] => 
          [port:protected] => 
          [timeout:protected] => 0
          [debug:protected] => 
          [exceptions:protected] => Array
              (
              )

          [client:protected] => 
          [totalHttpCalls:protected] => 0
          [Logger:protected] => 
          [refreshToken] => 
          [tokenExpiresAt] => 0
      )

**Comment by joeynovak** [comment]
Hmm....  Thanks for sending this in.  We're getting ready to really invest in version 2.0 so we can support the new rest api as well...  I'll look at this then.
