### ISSUE TITLE
Some Errors in APIAffiliateServiceBase.php

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#38]
In APIAffiliateServiceBase.php
You are using AffiliateService.affCommissions, I think it should be APIAffiliateService.affCommissions
same for affClawbacks, affSummary, ...

**Comment by joeynovak** [comment]
Yeah, there are several services where we have both API(ServiceName) and ServicName.  They need to be cleaned up, we will do this in 2.0 for sure, but we don't want to break compatibility at the moment.
