### ISSUE TITLE
Uninitialized variable in SmartCache

### ISSUE THREAD

**Issue by jchimene** [novaksolutions/infusionsoft-php-sdk#39]
When presented with an invalid cache filespec, SmartCache also fails with 
"$serialized_data not defined" error.

Adding an initialization of $serialized_data (line 69) will expose the invalid cache filespec error earlier in the cache initialization process.

```php
public function getDataFromCache(){ 
68	       $data = false;
69	       $serialized_data = ""; 
69	       if(self::$staticExternalCacheClass == null){ 	
70	           if(file_exists($this->getCacheFileName())){ 	
71	               $serialized_data = file_get_contents($this->getCacheFileName());

**Comment by joeynovak** [comment]
Cool, can you submit a PR?
