### ISSUE TITLE
How can we add a contact note?

### ISSUE THREAD

**Issue by elvismdev** [novaksolutions/infusionsoft-php-sdk#40]
I'm trying to find how to add a note to a contact record, however not luck yet on how to achieve this. Could you add to the examples in the wiki how can we do to add a note to a contact record?

Precisely this http://help.infusionsoft.com/userguides/contact-management/create-and-manage-contacts/add-a-note-to-a-contact-record but via the API using this SDK.

Thank you

**Comment by joeynovak** [comment]
Hey Elvis,

The record you are looking for is "ContactAction"  the contact action table holds notes, tasks, appointments, and more...  You would just do 

$contactAction = new Infusionsoft_ContactAction(); 
$contactAction->ContactId = $contactId; 
//(other stuff here to set the description, record type, etc...)
$contactAction->save();

I'm going to leave this issue open until we add this to the examples, but it may be a little while.

**Comment by elvismdev** [comment]
Hey thanks Joey, so yeah I figured it out finally doing some more research and trying until I got it. Here's part of my working code feel free to use it for your example.

```php
// Lookup sales person in InfusionSoft by his email so we can use his ID later.
$infusionSoftUserSearch = Infusionsoft_DataService::query( new Infusionsoft_User(), array( 'Email' => 'salesagent@mycomp.com' ) );
$infusionSoftUser = array_shift( $infusionSoftUserSearch );

$contactAction = new Infusionsoft_ContactAction();
$contactAction->ContactId = $contact->Id;
$contactAction->UserID = $infusionSoftUser->Id;
$contactAction->CompletionDate = date('Ymj\TG:i:s');
$contactAction->ActionDescription = 'My Note Title';
$contactAction->CreationNotes = 'My Note Description';
$contactAction->save();
```

Note that for my particular scenario where I wanted to create just a Note for the contact record I also needed to set a `CompletionDate` with the current time. Otherwise the note will be created but it also will show up as a Task in InfusionSoft.

I found this explained at this thread on the forums http://community.infusionsoft.com/showthread.php/1620-Notes-with-the-API?p=6389&viewfull=1#post6389

**Comment by joeynovak** [comment]
Awesome!  Thanks for the example, I just added it to our examples page.

**Comment by elvismdev** [comment]
I'd like to mention also something else I just find. If we want also to keep track of who created the note for the contact, e.g. which sales person did it, we'll have to drop this line as well

`$contactAction->CreatedBy = $infusionSoftUser->Id;`

If this is not included, then the note will show up in InfusionSoft like "Created By: System" instead something like "Created By: John Doe"

**Comment by bjosephpare** [comment]
Hi, we are in the process of updating from the XMLRPC to the REST api. Does this functionality currently exist in the REST api?
Thank you!

**Comment by freezey** [comment]
This question needs to be made to the Infusionsoft community. 
https://community.infusionsoft.com/c/api

**Comment by bjosephpare** [comment]
It was asked & answered here before, so I figured this was the place... I will ask there, thanks.
