### ISSUE TITLE
Get all tags for specific Contact

### ISSUE THREAD

**Issue by elvismdev** [novaksolutions/infusionsoft-php-sdk#41]
How can we get all the tags for a given contact id? I can see on the wiki an example on how to apply a tag to a contact by his id but cant find the method to get all the tags this specific contact has.

This could be added to the examples as well?

Thank you!

**Comment by joeynovak** [comment]
Hey,

There are two ways.  One is to use the Contact Groups field.  This is a Comma Seperated list of Tag Ids.  The other is the table ContactGroupAssign, this has a record for each tag a contact has.

Joey

**Comment by elvismdev** [comment]
Ops my bad, I always got the tags IDs here right on my Contact object as `[Groups] => 845,951,3436,4077`. I was looking more for something like `[Tags]` instead of `[Groups]`.

PD: InfusionSoft naming convention is soo confusing :(

**Comment by herbertgatchalian** [comment]
ContactGroupAssign is not working 

when i try list_objects.php?object=ContactGroupAssign
  
it gives me this error below

Fatal error: Uncaught [NoFieldFound]No field found: ContactGroupAssign.Contact.CustomDate1 Attempted: 1 time(s). thrown in D:\htdocs\SalesPageRepository\novak\Infusionsoft\App.php on line 157

**Comment by herbertgatchalian** [comment]
i wanted to list all groups a contactID is part of, can someone please help me find an example :(
