### ISSUE TITLE
Custom Fields for Orders/Invoices

### ISSUE THREAD

**Issue by praisedpk** [novaksolutions/infusionsoft-php-sdk#43]
Hi,

I am using this sdk and built application over it.
Now I need to add data for custom fields that I have already created through infusionsoft website, but the documentation does not state how this can be achieved. There is an example for contact table, but not for orders:
```
$contact = new Infusionsoft_Contact($_REQUEST['ContactId']);
$contact->_LeadScore = $contact->_LeadScore + 1;
```
After I create invoice and add items to it, what should I do next?
```
$invoiceId = Infusionsoft_InvoiceService::createBlankOrder($contact->Id, "An Order", date('Ymd\TH:i:s'));
Infusionsoft_InvoiceService::addOrderItem($invoiceId, $productId, 4, 3.99, 1, 'Order Item', '');
Infusionsoft_InvoiceService::addManualPayment($invoiceId, 3.99, date('Ymd\TH:i:s'), 'API', 'A Manual Payment from the API');
```

Im not very good with OOP, so need your help.

**Comment by praisedpk** [comment]
Any help!!

**Comment by joeynovak** [comment]
Yes, the object itself has a custom field list.  Invoices don't have custom fields, only jobs...  So, you would do:

$job = new Infusionsoft_Job($jobId); (You can get the jobid from the invoice).
$job->addCustomField("_FieldName"); (you don't need to do this on a per-object basis, this is a stupid mistake I made a long time ago, it is a non-static method that only updates a static member...  So just do this once).
$job->_FieldName = '';
$job->save();
