### ISSUE TITLE
 xmlrpcresp.php No such file or directory

### ISSUE THREAD

**Issue by wouterolwagen** [novaksolutions/infusionsoft-php-sdk#44]
PHP extension php_xmlrpc is enabled but I get this error when doing a post to our api using Yii when using the infusionsoft-php-sdk.

include(xmlrpcresp.php), No such file or directory

**Comment by joeynovak** [comment]
Interesting.  Can you post the full error, it should include what the include path is.  You can get better error messages if you install XDebug as well.
