### ISSUE TITLE
check Email, Host and key exist or not?

### ISSUE THREAD

**Issue by abhisirohi72** [novaksolutions/infusionsoft-php-sdk#49]
hello sir

I am new in infusionsoft. i want to know that how can we check user email, host and api key is exist or not in infusionsoft without login?

Thanks In Advance

**Comment by joeynovak** [comment]
I don't quite understand your question, can you re-phrase it?

**Comment by abhisirohi72** [comment]
hello sir
my php version is 5.2 
when i use your sdk then they show error
==================================
Parse error: syntax error, unexpected T_STATIC in /var/www/web1/web/api/infussionsoft/Infusionsoft/AppPool.php on line 67
=================================
is there any solution without to change my php version and they works fine

Thanks

**Comment by joeynovak** [comment]
There is not.  We choose to only support PHP 5.3 and up when we built the sdk.  A lot of things changed with static methods with 5.3, and it greatly facilitated the way we wanted to build it.

**Comment by abhisirohi72** [comment]
thanks a lot sir for your reply
