### ISSUE TITLE
Declaration of Infusionsoft_CustomFieldService::getCustomFields() should be compatible with Infusionsoft_DataService::getCustomFields($object, $app = NULL)

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#50]
When trying to use Infusionsoft_CustomFieldService, I'm getting this error message

PHP Strict Standards:  Declaration of Infusionsoft_CustomFieldService::getCustomFields() should be compatible with Infusionsoft_DataService::getCustomFields($object, $app = NULL) in Infusionsoft/CustomFieldService.php on line 136

**Comment by joeynovak** [comment]
Thanks for opening this, it keeps us on our toes.  We don't support Strict mode at the moment, there are quite a few errors there.  We developed this 8ish years ago.  So it's time for a 2.0 version, check out the dev branch. (Warning, it's in pre-alpha, so lots of stuff is still broken)  
We run so there are no notices, but strict, you will get errors.

We'll probably make the code strict compliant in 2.0 when we add namespacing, etc..
