### ISSUE TITLE
Infusionsoft_CustomFieldService getCustomField doesn't work with Multi App

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#51]
Infusionsoft_CustomFieldService getCustomField doesn't work with Multi App

$out = parent::query(new Infusionsoft_DataFormField(), $conditions, 1000);
needs to be changed to
$out = parent::query(new Infusionsoft_DataFormField(), $conditions, 1000, 0, false, $app);

**Comment by joeynovak** [comment]
Interesting.  Can you submit a pr for a fix for this?  Very few people use the multi-app capability so we're not even 100% sure we're going to carry it over to 2.0, but, we don't know yet :)
