### ISSUE TITLE
Unable to select all recipients in template created via API

### ISSUE THREAD

**Issue by shainanand** [novaksolutions/infusionsoft-php-sdk#54]
I added a template via API to the InfusionSoft account. But I am unable to send it to all the contacts in my account. How can I set the **To** address to all contacts via API?

**Comment by joeynovak** [comment]
You cannot.  You have to get the list of contact ids you want to send to, and then pass that list of ids into the APIEmailService::sendTemplate (iirc).  I almost never use this method myself, but I heard quite a few years ago, that if you send it to more then a few thousand contacts, it may fail silently, so I recommend you only send to a few thousand contacts at a time.
