### ISSUE TITLE
Unable to print error response

### ISSUE THREAD

**Issue by shainanand** [novaksolutions/infusionsoft-php-sdk#55]
I tried to retrieve a non-existing email template via **getEmailTemplate** function. But I could not print the error response. Instead my web page shows **[Unexpected]Unable to get email template Attempted: 1 time(s).**. Is there any way that I can print the response API from InfusionSoft?

**Comment by joeynovak** [comment]
There are some debug options, I believe on the Infusionsoft_App object that will record the request and response.  However, I have seen this quite a few times, some templates are not retrievable via the API for some reason.
