### ISSUE TITLE
Error while using DataService function

### ISSUE THREAD

**Issue by shainanand** [novaksolutions/infusionsoft-php-sdk#56]
I tried to use the **query ** function under **DataService**, but I got the following error:

> Error: Call to a member function getAppPoolAppKey() on a non-object	
> File: C:\xampp\htdocs\test\app\Vendor\infusionsoft-php-sdk-master\Infusionsoft\Service.php	
> Line: 52

**Comment by joeynovak** [comment]
This is almost always because the infusionsoft.php file wasn't loaded.

I'll add a better error message in there somewhere.

**Comment by shainanand** [comment]
But the file is loaded and I was able to access the getEmailTemplate function.

**Comment by joeynovak** [comment]
Can you send me your code?

**Comment by shainanand** [comment]
I was trying to get all the templates in my infusionsoft account.

`$app=new Infusionsoft_DataService();
$allTemplates= $app->search('Template', array( 'Id' => '%'), 10, 0);`
