### ISSUE TITLE
Contact Note or Person Notes Append?

### ISSUE THREAD

**Issue by cclambie** [novaksolutions/infusionsoft-php-sdk#57]
Hi there,

Could you clarify if this method is going to append to person notes field for a contact, or is going to create a "note" associated with the contact.
https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#create-a-contact-note

If as I expect, it is the later, is there a method I am missing to append to person notes?

Thanks
Craig

**Comment by joeynovak** [comment]
Correct, that will create a new "note" associated with the contact.
