### ISSUE TITLE
Opportunity Stage Change?

### ISSUE THREAD

**Issue by cclambie** [novaksolutions/infusionsoft-php-sdk#58]
Hi Novak's,
Thanks for this great SDK, I love it.
I am wondering if there is an in built tool for moving an opportunity from one stage to another?

I went to an IS User group last night, and found out about opportunities, and the reporting, which is much better and clearer on this, but the first 6 stages of a funnel for me are automated.
I would love to move a Lead through each stage automagically (ie. via the API) until the reach the stage of needing a person to interact.

I understand the API has this capability.  Does your SDK?
If so, I cannot see it in any examples.
I can see the "create opportunity" example, so I think you interact with this somewhere.
Maybe StageMove.php? MtgLead.php? or Lead.php? ContactAction.php?

I just cannot see the method for it.  I can see something about Stage, but not sure if this is really the stage inside an opportunity?
I was thinking there would be a function to 
1. Pull a list of possible stages, with their IDs
2. Push the StageFrom and StageTo based on these IDs?  They appear to be string fields, so maybe not.

I cannot find a method for actually using the class / table in StageMove.php, maybe I just don't follow the logic sorry, not as big a coder as I used to be.

I look forward to hearing from you :)

Cheers

C

**Comment by joeynovak** [comment]
Awesome, glad you like it.  I am pretty sure that if you just change the StageId of an opportunity and save it, the StageMove record is automatically created.  You can look at the Stages table to get a list of stage names to ids.
