### ISSUE TITLE
createBlankOrder: Uncaught no method matching arguments

### ISSUE THREAD

**Issue by ebertulfo** [novaksolutions/infusionsoft-php-sdk#6]
![image](https://cloud.githubusercontent.com/assets/7775108/3155235/ee3228e4-eabb-11e3-8713-520855a19418.png)

**Comment by silasrm** [comment]
I'm trying use this method and this error is returned:

No method matching arguments: java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer
Attempted: 1 time(s).

Parameters: ('InvoiceService.createBlankOrder', array('9', 'Curso de PHP', '2015-03-11T13:27:57-03:00', '0', '0'), false) .

This date is generated by: date('c');
c is the date format on ISO 8601 format. On example, yours using: date('Y-m-d H:i:s').

How fix this?

**Comment by jacoballred** [comment]
Can you provide the full line of code you are calling? It is difficult to troubleshoot with just the parameters.

**Comment by silasrm** [comment]
Hi Jacob,

My code:

$invoiceId = \Infusionsoft_InvoiceService::createBlankOrder(
            (int)$contactId, // returned by search or created before this call
            $matricula->getCategoria()->getNome(), // Name of my product. My sales is 1 product per sale.
            date("c")
        );

**Comment by jacoballred** [comment]
It looks like date("c") may be what is causing your problem. Infusionsoft's handling of ISO 8601 dates is extremely limited. Try this format:
date('Ymd\TH:i:s')

**Comment by silasrm** [comment]
Oww. With date('Ymd\TH:i:s') is ok.
But on php manual to date function, date('c') is to ISO 8601 format.

Thanks to help me. Fix the example code for Manual payment, the date is in wrong format :P

**Comment by jacoballred** [comment]
Yes, date('c') is valid ISO 8601 format. Infusionsoft has a bad habit of only half-implementing the standards they claim to support. The API can only handle a very specific version of ISO 8601.

I've updated the example code.

**Comment by silasrm** [comment]
Yelp. Thanks.

**Comment by joeynovak** [comment]
This same thing bit me Monday.  I'm thinking maybe we should put some code
there to put it in the right format no matter what is passed in for a
future release.

On Wed, Mar 11, 2015 at 10:07 AM, Jacob Allred <notifications@github.com>
wrote:

> It looks like date("c") may be what is causing your problem.
> Infusionsoft's handling of ISO 8601 dates is extremely limited. Try this
> format:
> date('Ymd\TH:i:s')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novaksolutions/infusionsoft-php-sdk/issues/6#issuecomment-78307985>
> .
>



-- 
Schedule a call with me: <http://goog_653805605> <http://goog_653805605>
http://doodle.com/joeynovak

C) 623-252-2387

Like Novak Solutions on Facebook
<http://www.facebook.com/plugins/like.php?href=http://www.facebook.com/pages/Novak-Solutions-LLC/282048461853879>

"Opportunity is missed by most people because it is dressed in overalls and
looks like work." --Thomas Edison

**Comment by silasrm** [comment]
To fix on manual payment example, on the line of Infusionsoft_InvoiceService::addManualPayment, the parameter number 6 is not passed: $bypassCommissions.

About date format error, if accept Y-m-d H:i:s, convert to Ymd\TH:i:s and voilá.

**Comment by MarcFowler** [comment]
I know this issue is super old but I wanted to bump everyone here and thank you all. I ran into a problem, using a totally different SDK to interface with Infusionsoft, this was the top result and it solved my problem immediately - my date was formatted wrongly. Thanks!!
