### ISSUE TITLE
Unable to get list of contact Ids from Infusionsoft

### ISSUE THREAD

**Issue by shainanand** [novaksolutions/infusionsoft-php-sdk#61]
I want to get list of contact Ids from Infusionsoft so that I can check whether the Id stored in my database exist in Infusionsoft. Is there any other way to do it?

**Comment by joeynovak** [comment]
When you do infusionsoft_DataService::query(...) one of the arguments is a field list.  If you pass in a field list, you'll still get back a list of objects, but only the fields you specify will be loaded.

So something like...

Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Id' => '%'), (something, something) , (fieldlist));

**Comment by shainanand** [comment]
Thank you so much

**Comment by herbertgatchalian** [comment]
how do i query all the contactId with same specific email address ? like 

select * from contacts WHERE email = john@yahoo.com 

i tried this below and it is only displaying 1 contact, it wont continue with the others 

$class_namex = "Infusionsoft_Contact";
$objectx = new $class_namex();
$objectsx = Infusionsoft_DataService::query(new $class_namex(), array('Email' => $object->' john@yahoo.com'));


what i am trying to accomplish is display both contactId 147 and 74 which has the same email address john@yahoo.com
