### ISSUE TITLE
Not sure why FileService not working

### ISSUE THREAD

**Issue by plugged4** [novaksolutions/infusionsoft-php-sdk#62]
Trying to do a simple form to upload to a contacts filebox, and I'm not sure why it's not working. I'm sure I'm going to have a "Duh" moment, but here is the form code and the PHP uploader to Infusionsoft.

Form Code:
````
function tagger_upload_form( $current_user_contact_id, $thanksPage ) {
	if( is_user_logged_in() ) {
		echo '<form enctype="multipart/form-data" action="' . plugins_url( 'ifstagger/inc/ifsuploader.php' , dirname(__FILE__) ) . '" method="post">';
		echo '<input type="hidden" name="contact" value="' . $current_user_contact_id . '">';
		echo '<input type="hidden" name="thanksPage" value="' . $thanksPage . '">';
		echo '<p>';
		echo 'Completed Exercise: <input id="tagger_upload" type="file" name="filebox" required>';
		echo '</p>';
		echo '<p>';
		echo '<input type="submit" value="Upload">';
		echo '</p>';
	}
	else {
		echo '';
	}
}
````

Uploader PHP file
````
if ($_SERVER["REQUEST_METHOD"] == "POST") {
     //ready file for upload

     $fileName = basename($_FILES['filebox']['name']);
     $data = file_get_contents($_FILES['filebox']['tmp_name']);
     $base64encoded = base64_encode($data);
     $contactId = $_POST['contact'];
     $thanksPage = $_POST['thanksPage'];

     //upload file to Infusionsoft FileBox
     Infusionsoft_FileService::uploadFile($contactId, $fileName, $base64encoded);
	 header('Location: ' . $thanksPage);
}
else {
     // Not a POST request, set a 403 (forbidden) response code.
        http_response_code(403);
        echo "There was a problem with your submission, please try again.";
}
````

**Comment by joeynovak** [comment]
Interesting, what is happening when it doesn't work?  Also, do you have any logs or a way to see errors?  I like to turn Notices on, as that frequently shows me the problem as well.

**Comment by plugged4** [comment]
I was getting sent to the uploader.php page (location header change wasn't happening) but it was blank. After turning on notices, I get:

Fatal error: Class 'Infusionsoft_FileService' not found in ~removed my site~/wp-content/plugins/ifstagger/inc/ifsuploader.php on line 14

However in the same file as the one the form code is built in, I have

'Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => $email));'

and it is working perfectly fine.

**Comment by joeynovak** [comment]
PHP Doesn't lie, so for some reason it can't find that file, either the autoloader isn't loading, or the class is missing for some reason, etc..  You can try to manually include it, but I have NEVER seen our Autoloader not work.   I would try making a simpler file that just uses the fileservice to upload some static data on your server. (i.e. just a simple php page, you hit it, and it creates a file in the file box with data like "abcde" or something) get that working and you'll probably discover your problem, but I am 95% sure it isn't a problem with the SDK.
