### ISSUE TITLE
Displaying order details on a page

### ISSUE THREAD

**Issue by dipaksaraf** [novaksolutions/infusionsoft-php-sdk#64]
I am using the WordPress version of the Php SDK & on one of the Thank You page I have added the following codes>> 

`<?php
extract($_GET);
$orderItems = Infusionsoft_DataService::query(new Infusionsoft_OrderItem(), array('OrderId' => $orderId));
$saleAmt = 0;
foreach ($orderItems as $item) {
    $saleAmt += $item['Qty'] * $item['PPU'];
}

print_r($orderItems);
print_r($orderItems['Qty']);
print_r($orderItems['PPU'];
print_r($saleAmt);

?>`

I doesnt work however if I use the following code >> 

`<?php
extract($_GET);
$orderItems = Infusionsoft_DataService::query(new Infusionsoft_OrderItem(), array('OrderId' => $orderId));

print_r($orderItems);

?>`

I works and outputs following details 
![isoutput](https://cloud.githubusercontent.com/assets/2611299/15296055/320b2ac0-1bb1-11e6-8b54-afefab21a6e3.JPG)

Not sure where I am doing wrong or incorrectly. A help in this would be appreciated.

Thanks
Dipak

**Comment by joeynovak** [comment]
Hi Dipak,

Our SDK is object based, not array based.  So you'd need to do print_r($orderItem->PPU).  

Also, extract($_GET) is very dangerous.  It would allow anyone to add a variable to your code, which, for simple code like you've posted above won't hurt anything, but it has the ability to be very bad if you make a mistake.

Joey
