### ISSUE TITLE
Can we check email if it exist or not?

### ISSUE THREAD

**Issue by vijaykc** [novaksolutions/infusionsoft-php-sdk#65]
Is there a way to check if contact/email exist or not?

Create new contact 
```
include('Infusionsoft/infusionsoft.php');
$contact = new Infusionsoft_Contact();
$contact->FirstName = 'John';
$contact->LastName = 'Doe';
$contact->save();

```
This code create unlimited contact? Does it check duplicate? Each time i run it and get new id. Is that mean it create unlimited contact?

**Comment by joeynovak** [comment]
Yeah, that means it just keep creating them over and over.

To check by email, you do:
$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => $email));

The do, 
if(count($contacts) > 0){
  $contact = array_shift($contacts);
} else {
  $contact = new Infusionsoft_Contact();
}

**Comment by vijaykc** [comment]
Thanks Novak. :+1:

**Comment by andrelmariano** [comment]
Hello Novak, and how would I update a field of this contact that already exists?
