### ISSUE TITLE
Pull Contacts by Tag Name

### ISSUE THREAD

**Issue by eddiedotdev** [novaksolutions/infusionsoft-php-sdk#7]
I've been working with your code and so far it works great. I'm able to pull all the contacts by fieldname. This is what my pull looks like:

```
$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Id' => '%', 'State' => 'CA'));
```

What I need to know is how to also add a custom tag to the pull. My client has added a custom tag to specific contacts "Certified Agents" and only want those with that tag applied to show up. I know there's a way to do it with your class but I'm not sure how to. 

Any help would be fantastic. Thanks!

**Comment by swarnenduDutta** [comment]
Infusionsoft_Exception: [NoFieldFound]No field found: ContactGroup.Group Name Attempted: 1 time(s). m getting this error

**Comment by trinidado007** [comment]
That s awesome. Not my question is , how can i retrieve all my contact without any conditions?

**Comment by chitranshbhalla** [comment]
$all_contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(),
array('Id' => '%'));
