### ISSUE TITLE
Contacts come in as unmarketable

### ISSUE THREAD

**Issue by SenorLAN** [novaksolutions/infusionsoft-php-sdk#70]
I have the SDK set up for a portal page that collects the user information and by submitting they agree to Ts&Cs to be marketed to. The contacts from this come into IS and are properly tagged, but they are all listed as unmarketable. Is there a value I need to pass along to opt them in or change them somehow to at least "unverified" status in IS?

**Comment by joeynovak** [comment]
Hey, quick answer, you have to optin email addresses using the email
service optin call

**Comment by malle-pietje** [comment]
@joeynovak Thanks for that input! I'm the one doing the implementation for @SenorLAN and have an additional question: since this function only uses email, does that mean the optin "flag" applies to all contacts with that email address?

**Comment by joeynovak** [comment]
Correct, Infusionsoft has no concept of "Contacts" being opted in.  It's
all email address based.

**Comment by malle-pietje** [comment]
@joeynovak thanks for confirming; good to know :+1:

**Comment by ampped101** [comment]
Firstly, thanks so much for this great API. It is much appreciated. Do you have an example of using APIEmailService.optIn with PHP ? Some emails are coming in as marketable and some of them are not.

**Comment by malle-pietje** [comment]
@ampped101 Who are you asking? Here's an example of what I did after the suggestion from @joeynovak :
```        /*
        set opt-in for given email address
        Infusionsoft_EmailService->optIn($email,  $permissionReason)
        */
        $optin = new Infusionsoft_EmailService();
        $optin->optIn($emailaddress, 'Agreed to bla bla terms');
```

**Comment by ampped101** [comment]
Thanks @malle-pietje , But I am not super proficient in programming and have used the current examples to add contacts to the list.

Where do I add this code? 

   /*
        set opt-in for given email address
        Infusionsoft_EmailService->optIn($email,  $permissionReason)
        */

Or does it already exist in the api somewhere?

**Comment by malle-pietje** [comment]
Place something like this in your own custom code where you include the API where $emailaddress is the address you wish to opt-in. My example simply calls the optin() function in the EmailService class.
