### ISSUE TITLE
saveTokens() is a non-object

### ISSUE THREAD

**Issue by by225** [novaksolutions/infusionsoft-php-sdk#73]
Now getting this error:

Fatal error: Call to a member function saveTokens() on a non-object in .../Infusionsoft/App.php on line 204

**Comment by packytagliaferro** [comment]
I am also getting an error on that line

`
Fatal error: Uncaught Error: Call to a member function saveTokens() on null in ********/build/custom_api/Infusionsoft/App.php:204 Stack trace: #0 ********build/custom_api/Infusionsoft/OAuth2.php(92): Infusionsoft_App->updateAndSaveTokens('8fbk8eyeqyhafax...', 'eqqc4ha5gy36wss...', 86400) #1 ********/build/custom_api/Infusionsoft/OAuth2.php(75): Infusionsoft_OAuth2::processAuthenticationScopeAndCode('full', 's9xvhh9xpdet8sq...') #2 ********/build/app/views/layouts/header.php(23): Infusionsoft_OAuth2::processAuthenticationResponseIfPresent() #3 ********/build/app/views/home.php(1): require('/Users/PackyTag...') #4 ********/build/Config.php(21): include('/Users/PackyTag...') #5 ********/build/index.php(4): include_once('/Users/PackyTag...') #6 {main in ********/build/custom_api/Infusionsoft/App.php on line 204`
