### ISSUE TITLE
Creating a blank order using the createBlankOrder method and amending the shipping address

### ISSUE THREAD

**Issue by joe-j-harris** [novaksolutions/infusionsoft-php-sdk#74]
I have been integrating your infusionsoft library for a business web app and has worked great so far... so first of all thank you.

Ive looked at your examples and there are two things not documented.

1/ Is it possible to add multiple tags in a single API call using Infusionsoft_ContactService::addToGroup($contactID, $groupID);?

2/ After using the createBlankOrder method how can you update the shipping address?

Please advise.

Regards

Joe

**Comment by joeynovak** [comment]
Hey Joe,

I don't know of a way to add more then one tag in one call.  As for #2, Is
it available in the Jobs table?  If it isn't, then there may not be a way
to do that.

Joey

**Comment by joe-j-harris** [comment]
Hi Joey,

Thanks for your response. The Shipping details are in the jobs table. How would I reference this job using the CreateBlankOrder method?

Regards

Joe

**Comment by joeynovak** [comment]
Jobs are Orders.  I don't recall if CreateBlankOrder gives you back an
InvoiceId or a JobId, but you can use either one to find the JobId, I think
if you get InvoiceId, you have to then load the Invoice to get the JobId.
