### ISSUE TITLE
Accessing Contact Info

### ISSUE THREAD

**Issue by packytagliaferro** [novaksolutions/infusionsoft-php-sdk#76]
When I query Infusionsoft API like:
`
Infusionsoft_DataService::findByField(new Infusionsoft_Contact(),'Email', $user_email );`

I get the info I need but cant access the info through the array is it returns a protected object like:

```
object(Contact)#165 (5) {
  ["customFieldFormId"]=>
  int(-1)
  ["fields":protected]=>
  NULL
  ["table":protected]=>
  string(7) "Contact"
  ["data":protected]=>
  array(78) {
    ["Id"]=>
    '1' 
```

Am I missing something? I need to get contact info

**Comment by jacoballred** [comment]
You might find the examples page helpful: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples

If your contact object is named $contact and you wanted to get the first name, you'd do something like this:
`$contact->FirstName`

The Infusionsoft table documentation can provide all the field names available: https://developer.infusionsoft.com/docs/table-schema/

**Comment by packytagliaferro** [comment]
Perfect, This makes a lot more sense. Thanks. 

One other thing, how can I get the contacts CC info to update if needed? I tried but doesn’t return anything:

$contact_cc = Infusionsoft_DataService::findByField(new Infusionsoft_CreditCard(), 'ContactId', $user_IS_id);
