### ISSUE TITLE
query list of contacts

### ISSUE THREAD

**Issue by herbertgatchalian** [novaksolutions/infusionsoft-php-sdk#79]
how do i query all the contactId with same specific email address ? like

select \* from contacts WHERE email = john@yahoo.com

i tried this below and it is only displaying 1 contact, it wont continue with the others

$class_namex = "Infusionsoft_Contact";
$objectx = new $class_namex();
$objectsx = Infusionsoft_DataService::query(new $class_namex(), array('Email' => ' john@yahoo.com'));

foreach($objectsx as $objectx){ echo $objectx->Id; }

what i am trying to accomplish is display both contactId 147 and 74 which has the same email address john@yahoo.com

**Comment by packytagliaferro** [comment]
I know you have something similar but this works for me:

```
$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => 'AN EMAIL'));

foreach($contacts as $contact)
{
  echo $contact->Id; 
}
```

**Comment by alex-kowalski** [comment]
Please try this.

`$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Email' => 'AN EMAIL'), 1000, 0, array('Id'), $infusionsoft);`

_$infusionsoft_ is _Infusionsoft_App_ object.
