### ISSUE TITLE
Accented consonant characters aren't filtered

### ISSUE THREAD

**Issue by jchimene** [novaksolutions/infusionsoft-php-sdk#8]
The character ć isn't filtered. I'd like to propose a patch, but I'm not sure where in the xmlrpc this is handled. I suspect other accented consonants also must be filtered.

**Comment by joeynovak** [comment]
Hey Jeff,

Is this still an issue?  If so, I'd like to look into it.

Joey

**Comment by jchimene** [comment]
It's no longer an issue in the sense that I worked around it by grabbing the WordPress routine that's responsible for user name cleanup and sending the results to Infusionsoft.
