### ISSUE TITLE
Webform service breaks site (white screen)

### ISSUE THREAD

**Issue by packytagliaferro** [novaksolutions/infusionsoft-php-sdk#81]
How are the webforms handled? From the looks of it I should be able to do 

`$webform = new Infusionsoft_WebFormService::getHTML(3);`

where 3 is the id of the for but I get this error:

`<b>Parse error</b>:  syntax error, unexpected 'getHTML' (T_STRING), expecting variable (T_VARIABLE) or '$'`

**Comment by jacoballred** [comment]
Looks like a simple PHP mistake. You need to remove `new` when accessing a static method.
