### ISSUE TITLE
Leadscore available in API?

### ISSUE THREAD

**Issue by heydey** [novaksolutions/infusionsoft-php-sdk#85]
Hello,

One of your examples is to update the Leadscore. While everything else was pretty easy to get up and running, I'm not able to retrieve or update the Leadscore. 

The example:

```
Infusionsoft_Contact::addCustomField('_LeadScore');
    $contact = new Infusionsoft_Contact($_REQUEST['ContactId']);
    $contact->_LeadScore = $contact->_LeadScore + 1;
    $contact->save();

```

I can't seem to find any documentation anywhere else on this either.
Fantastic API btw, much easier to get started with than the official. Thanks!

**Comment by rabrenio** [comment]
For you to add value to _LeadScore you first need to tell the SDK that the custom fields exist by usings this lline:

```
//add this after calling the class
$contact->addCustomFields(array('_LeadScore'));
//and then set the value
$contact->_LeadScore = 'any value';
$contact->save();

```

**Comment by jacoballred** [comment]
The lead score generated by Infusionsoft isn't available via the API. Many people create a custom field for lead score and populate it using their own criteria.
