### ISSUE TITLE
 Error: [Exception] Invalid Field Name: _Passcode

### ISSUE THREAD

**Issue by bringerofrain** [novaksolutions/infusionsoft-php-sdk#87]
Getting this error when following the example verbatim with a contact Id and verified Custom field name

$isContact = new Infusionsoft_Contact($contactID);
$isContact->_Passcode = 'test';
$isContact->save();

**Comment by jacoballred** [comment]
Did you update your configuration file so it knows about the custom field? See: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#installation

**Comment by bringerofrain** [comment]
Thank you, I'm amazed at for how long I do this I can miss simple things like that.  Sorry for the issue ticket.
