### ISSUE TITLE
How to retrieve all the information of all the Contact in infusionsoft?

### ISSUE THREAD

**Issue by trinidado007** [novaksolutions/infusionsoft-php-sdk#88]
I would like to retrieve all the information of all the users on my infusionsoft account with any condition. Without specifying tags and stuff. Is it possible?

$contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Id' => 11));
print_r($contacts );

I don't want to specify any Id, i just want to get all the contacts.

Please help

**Comment by cclambie** [comment]
I believe the exporter.php file will do this, have you tried it? I am having trouble with an "Unexpected End of File" error coming up... :(
Is it working for you?
