### ISSUE TITLE
Add contact to a campaign

### ISSUE THREAD

**Issue by shanprabu** [novaksolutions/infusionsoft-php-sdk#89]
Hi,
I have created a new campaign and have built a page in php to capture customer details related to this campaign. I can add the contact to my Infusionsoft application. How can I add this contact to the campaign?

**Comment by jacoballred** [comment]
You have several options.

For example, you could add a tag to the contact using the API and have the tag as a goal in the campaign.

Another option would be to use an API campaign goal, as shown on our website: https://novaksolutions.com/tips/achieve-an-infusionsoft-campaign-goal-with-an-api-call/

**Comment by QamarRafhan** [comment]
Hi,

I have created a campaign, I want to add new contact to campaign through SDK.
How can I add this contact to the campaign?

http://prntscr.com/cw5l5m
http://prntscr.com/cw5ked

Thanks
