### ISSUE TITLE
Can't send email with the API

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#90]
When I try to send an email using Infusionsoft_APIEmailService::sendEmail,
I get :
PHP Fatal error:  Uncaught Failed to invoke method sendEmail in class com.infusionsoft.api.xmlrpc.XmlRpcEmailService: For input string: ""
Attempted: 1 time(s).
  thrown in /home/wphelpcl/subs/members/wp-content/plugins/AA-Addons/includes/Infusionsoft/App.php on line 157

Thanks,

Olivier

**Comment by jacoballred** [comment]
Can you provide an example of the code you are using?

**Comment by odoremieux** [comment]
Infusionsoft_APIEmailService::sendEmail(array('1234'),"myemail@foo.com","~Contact.Email~", "","","Text","My Subject","My Email body Text","My Email body Text");

**Comment by jacoballred** [comment]
The error you are getting is from Infusionsoft. Is 1234 a valid contact ID? Does the contact have an email address set?

**Comment by odoremieux** [comment]
My Bad, the Id was empty.
Sorry about that
