### ISSUE TITLE
Is Infusionsoft_ContactService::save supposed to work?

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#91]
Hi,

I'm trying some similar code to :
$out = Infusionsoft_ContactService::save($contact);

But I'm getting : PHP Fatal error:  Uncaught Error: Call to undefined method Infusionsoft_ContactService::save()

Is that API supposed to work? I did find the code in tests.

Otherwise what's the best way to save a contact after it has been modified?

I did try 
$contact1->save(); 
after changing $contact1->Groups , but it doesn't look like it's working.

Thanks in advance,

Olivier

**Comment by jacoballred** [comment]
Infusionsoft stores groups/tags in separate tables. You can't edit the contact directly to change the tags that a contact has.

The examples wiki page shows how to add tags to a contact: https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#add-a-tag-to-a-contact

Removing a tag is similar, using Infusionsoft_ContactService:removeFromGroup().
