### ISSUE TITLE
addCustomField

### ISSUE THREAD

**Issue by odoremieux** [novaksolutions/infusionsoft-php-sdk#92]
Does addCustomField dynamically creates Custom Fields, or it just allow to use a Custom Field with a Contact?

**Comment by clifgriffin** [comment]
@odoremieux I can answer this. It just allows you to use a custom field with the contact object. You still have to add the custom field manually through InfusionSoft.

**Comment by jimsdeveloper** [comment]
@odoremieux - How do I retrieve the value in _LeadScore? I am able to retrieve values for all the custom fields that I have defined inside Infusionsoft except for _LeadScore. I keep getting an error. Would appreciate any help to resolve this issue.

**Comment by jacoballred** [comment]
Have you confirmed you are using the correct custom field name? See: http://help.infusionsoft.com/related-articles/backend-database-names-for-custom-fields

What error message are you getting?

**Comment by jimsdeveloper** [comment]
This is the error I keep getting

> [NoFieldFound]No field found: Contact._LeadScore

_LeadScore doesn't show up in the list of "Backend Database names for custom fields". But when I go to my Infusionsoft account and check under CRM > Settings > Scores - I can see the list of rules to increment the Lead Score.

**Comment by odoremieux** [comment]
I was able to add a custom to IS by using  Infusionsoft_DataService::addCustomField. The trick was to get the right tab id.
To read / use it you have to add it to the contact first. So you have to get your contact first, then 
$contact->addCustomField('_LeadScore');
Then you can use $contact->_LeadScore'

**Comment by jacoballred** [comment]
The lead score generated by Infusionsoft isn't available via the API. Many people create a custom field for lead score and populate it using their own criteria.
