### ISSUE TITLE
Add contact to a campaign through SDK.

### ISSUE THREAD

**Issue by QamarRafhan** [novaksolutions/infusionsoft-php-sdk#93]
Hi,

I have created a campaign, I want to add new contact to campaign through SDK.
How can I add this contact to the campaign?

http://prntscr.com/cw5l5m
http://prntscr.com/cw5ked

Thanks

**Comment by QamarRafhan** [comment]
Still waiting for answer

**Comment by jacoballred** [comment]
The answer was already given in the other issue you commented on: https://github.com/novaksolutions/infusionsoft-php-sdk/issues/89
