### ISSUE TITLE
Inaccessible protected data

### ISSUE THREAD

**Issue by rabrenio** [novaksolutions/infusionsoft-php-sdk#94]
When trying to query data using DataService, the data is protect because it inherits from the Base Generator Class. How am I going to access the data if it is protected? By the way I am trying to access ContactGroup passing Infusionsoft_ContactGroup via DataService.

**Comment by joeynovak** [comment]
You don't access the data array directly, it is exposed via Properties (via
the magic __Get and __set methods)  this has an added advantage of
providing automatic code completion if you are using an IDE.

**Comment by rabrenio** [comment]
Can you provide me an example?
