### ISSUE TITLE
Remove contact from tag/group?

### ISSUE THREAD

**Issue by dustingtaylor** [novaksolutions/infusionsoft-php-sdk#96]
Is there a way to remove a contact from a group/tag? I'm familiar with this to add:

Infusionsoft_ContactService::addToGroup($contactID, $tagID);

Would there be something like this to remove?

Infusionsoft_ContactService::removeFromGroup($contactID, 8266);

**Comment by calebtr** [comment]
Yes, that's the method for removing a contact from a group - see the code at https://github.com/novaksolutions/infusionsoft-php-sdk/blob/c91d6f8c76ad8074028e0b8bb29372315c34c588/Infusionsoft/ContactServiceBase.php. 

It is also worth noting that this library matches well with the method names and order of parameters in the documentation for the Infusionsoft XML-RPC API, e.g. https://developer.infusionsoft.com/docs/xml-rpc/#contact-remove-a-tag-from-a-contact. If you can find the method in the official documentation, it would be a surprise if it isn't covered here.
