### ISSUE TITLE
Looking for ideas on how to retrieve order id for a contact id or email

### ISSUE THREAD

**Issue by dipaksaraf** [novaksolutions/infusionsoft-php-sdk#97]
I want to retrieve the order id for a particular contact id. Is it possible using API or any idea's on how to retrieve it

**Comment by NiveditaCreolestudios** [comment]
Hi, you can do it in this way for one particular contact id through php sdk

$userIds = //here you will have to mention the contact id of infusionsoft i.e infusionsoft_id;
$returnFields = array('Id','ContactId','OrderStatus'); //these are the return fields that you want.
$query = array('ContactId' =>$userIds,'OrderStatus' =>0);
$orderData = $app->dsQuery("Job",300,0,$query,$returnFields);
