### ISSUE TITLE
addManualPayment: Failed to invoke method addManualPayment

### ISSUE THREAD

**Issue by MJunaidAhmad** [novaksolutions/infusionsoft-php-sdk#98]
![ierror](https://cloud.githubusercontent.com/assets/12229238/20172538/51106660-a757-11e6-814d-b3082474dffb.PNG)
I am trying to manually add payment to an order after adding some order items to a blank order. 
Code is corrcect(syntatically). But getting error as showing in the picture above...
Below is my code:
$invoiceID=$infusionsoft->invoices()->createBlankOrder($contactID, 'New Test Order by Junaid', $d, 0, 0);

$re=$infusionsoft->invoices()->addOrderItem($invoiceID, 4, 4, 200.0, 1, 'This is New test item added by junaid', 'New testing by junaid','');	

$infusionsoft->invoices()->addManualPayment(160, 10.32, $d, 'API', 'New Test Payment by juanid',false);

**Comment by mcretien** [comment]
Have you found out what it was? Same issue here.

**Comment by jacoballred** [comment]
Are you using the SDK created by Infusionsoft or Novak Solutions? The code you posted doesn't look like our SDK. You'll need to contact Infusionsoft if you need help with their SDK.

Have you looked at the example code for creating an order and adding a manual payment? https://github.com/novaksolutions/infusionsoft-php-sdk/wiki/Examples#create-an-order-and-add-a-manual-payment

**Comment by MJunaidAhmad** [comment]
@mcretien check my answer here: http://stackoverflow.com/questions/39059409/adding-a-manual-payment-to-invoice-order-in-infusionsoft/40542025#40542025
may be it can help you.
