### ISSUE TITLE
Unexpected EOF in exporter.php

### ISSUE THREAD

**Issue by cclambie** [novaksolutions/infusionsoft-php-sdk#99]
Hi Joey and fellow developers,

Just trying out the exporter tool, and found a bug I believe.
"syntax error, unexpected end of file in ..." ..../examples/exporter.php file

I have tried a few things, like adding 
` else { echo "test"; }` 
to the file, which makes the error go away, but I don't see with the form, or any other results.  I have also tried a few other bug fixing things I can think of, but I am no PHP expert, so I am stuck.
Anyone else having this issue? I have tried in 2 environments, same outcome.

**Comment by mzike** [comment]
If you are running this under PHP7 you'll need to change the `<?` at the end of line 53 to `<?php`
